import { environment } from '@env';
import type * as M from '../models/realestate.models';
import type * as E from '../models/realestate.enums';

const BASE = `${environment.apiBaseUrl}/api/realestate`;

/**
 * Builds a query string, dropping anything undefined, null or blank.
 *
 * A plain object is flattened one level rather than stringified, because a query DTO on the
 * server binds from individual query parameters — sending `query=[object Object]` would arrive as
 * an unfiltered list, and nobody would notice until a page of the wrong data was already on screen.
 */
function qs(params: Record<string, unknown>): string {
  const search = new URLSearchParams();

  const add = (key: string, value: unknown): void => {
    if (value === undefined || value === null || value === '') return;

    if (Array.isArray(value)) {
      for (const item of value) if (item !== undefined && item !== null) search.append(key, String(item));
      return;
    }

    if (typeof value === 'object') {
      for (const [k, v] of Object.entries(value as Record<string, unknown>)) add(k, v);
      return;
    }

    search.set(key, String(value));
  };

  for (const [key, value] of Object.entries(params)) add(key, value);

  const text = search.toString();
  return text ? `?${text}` : '';
}

/**
 * Every Real Estate endpoint in one place.
 *
 * Kept as a literal map rather than string concatenation at the call site, so a route rename is a
 * single edit and the module's whole API surface can be read without opening Swagger.
 */
export const REALESTATE_API = {
  hub: `${environment.apiBaseUrl}/hubs/realestate`,

  admin: {
    getSettings: `${BASE}/admin/settings`,
    updateSettings: `${BASE}/admin/settings`,
    getLinesOfBusiness: `${BASE}/admin/lines-of-business`,
    getOffices: (query?: M.ListQueryDto) => `${BASE}/admin/offices${qs({ query })}`,
    getOffice: (id: string) => `${BASE}/admin/offices/${id}`,
    saveOffice: `${BASE}/admin/offices`,
    getGeoTree: (parentId?: string, depth?: number) => `${BASE}/admin/geo${qs({ parentId, depth })}`,
    searchGeo: (search?: string, take?: number) => `${BASE}/admin/geo/search${qs({ search, take })}`,
    saveGeo: `${BASE}/admin/geo`,
    deleteGeo: (id: string) => `${BASE}/admin/geo/${id}`,
    getTerritories: (officeId?: string) => `${BASE}/admin/territories${qs({ officeId })}`,
    saveTerritory: `${BASE}/admin/territories`,
    getAgents: (query?: M.ListQueryDto) => `${BASE}/admin/agents${qs({ query })}`,
    getAgent: (id: string) => `${BASE}/admin/agents/${id}`,
    saveAgent: `${BASE}/admin/agents`,
    getAgentLookup: (officeId?: string) => `${BASE}/admin/agents/lookup${qs({ officeId })}`,
    getTeams: (officeId?: string) => `${BASE}/admin/teams${qs({ officeId })}`,
    saveTeam: `${BASE}/admin/teams`,
    getReasonCodes: (context?: string) => `${BASE}/admin/reason-codes${qs({ context })}`,
    saveReasonCode: `${BASE}/admin/reason-codes`,
    getMatrix: (documentType?: string) => `${BASE}/admin/approval-matrix${qs({ documentType })}`,
    saveMatrix: `${BASE}/admin/approval-matrix`,
    getApprovals: (query?: M.ListQueryDto, mineOnly?: boolean) => `${BASE}/admin/approvals${qs({ query, mineOnly })}`,
    decideApproval: `${BASE}/admin/approvals/decide`,
    getViews: (screenKey?: string) => `${BASE}/admin/views${qs({ screenKey })}`,
    saveView: `${BASE}/admin/views`,
    deleteView: (id: string) => `${BASE}/admin/views/${id}`,
    runImport: `${BASE}/admin/imports`,
    getImports: (query?: M.ListQueryDto) => `${BASE}/admin/imports${qs({ query })}`,
    getImport: (id: string) => `${BASE}/admin/imports/${id}`,
    commitImport: (id: string) => `${BASE}/admin/imports/${id}/commit`,
    rollbackImport: (id: string) => `${BASE}/admin/imports/${id}/rollback`,
  },

  booking: {
    getOffers: (query?: M.ListQueryDto, propertyId?: string, status?: E.OfferStatus) => `${BASE}/bookings/offers${qs({ query, propertyId, status })}`,
    getOffer: (id: string) => `${BASE}/bookings/offers/${id}`,
    saveOffer: `${BASE}/bookings/offers`,
    decideOffer: `${BASE}/bookings/offers/decide`,
    getEois: (query?: M.ListQueryDto, projectId?: string) => `${BASE}/bookings/eois${qs({ query, projectId })}`,
    saveEoi: (withPayment?: boolean) => `${BASE}/bookings/eois${qs({ withPayment })}`,
    refundEoi: (id: string) => `${BASE}/bookings/eois/${id}/refund`,
    getTokens: (query?: M.ListQueryDto, projectId?: string, status?: E.ReservationStatus) => `${BASE}/bookings/tokens${qs({ query, projectId, status })}`,
    createToken: `${BASE}/bookings/tokens`,
    cancelToken: (id: string, reasonCodeId?: string, forfeit?: boolean) => `${BASE}/bookings/tokens/${id}/cancel${qs({ reasonCodeId, forfeit })}`,
    expireTokens: `${BASE}/bookings/tokens/expire`,
    search: `${BASE}/bookings/search`,
    get: (id: string) => `${BASE}/bookings/${id}`,
    preview: `${BASE}/bookings/preview`,
    create: `${BASE}/bookings`,
    approve: `${BASE}/bookings/approve`,
    confirm: (id: string) => `${BASE}/bookings/${id}/confirm`,
    requestAmendment: `${BASE}/bookings/amendments`,
    decideAmendment: (id: string, outcome?: E.ApprovalOutcome, comment?: string) => `${BASE}/bookings/amendments/${id}/decide${qs({ outcome, comment })}`,
    issueAllotment: (id: string, templateId?: string) => `${BASE}/bookings/${id}/allotment${qs({ templateId })}`,
    reissueAllotment: (id: string, reason?: string) => `${BASE}/bookings/allotments/${id}/reissue${qs({ reason })}`,
    getAllotments: (query?: M.ListQueryDto, projectId?: string) => `${BASE}/bookings/allotments${qs({ query, projectId })}`,
    generateAgreement: (id: string, templateId?: string, languageCode?: string) => `${BASE}/bookings/${id}/agreement${qs({ templateId, languageCode })}`,
    recordExecution: (id: string, executedOn?: string, registrationNumber?: string) => `${BASE}/bookings/agreements/${id}/execution${qs({ executedOn, registrationNumber })}`,
    getBallots: (query?: M.ListQueryDto, projectId?: string) => `${BASE}/bookings/ballots${qs({ query, projectId })}`,
    getBallot: (id: string) => `${BASE}/bookings/ballots/${id}`,
    saveBallot: `${BASE}/bookings/ballots`,
    lockPool: (id: string) => `${BASE}/bookings/ballots/${id}/lock`,
    draw: `${BASE}/bookings/ballots/draw`,
    publishBallot: (id: string) => `${BASE}/bookings/ballots/${id}/publish`,
    getBallotEntries: (id: string, categoryId?: string) => `${BASE}/bookings/ballots/${id}/entries${qs({ categoryId })}`,
    overrideAllocation: (entryId: string, unitId?: string, reason?: string) => `${BASE}/bookings/ballots/entries/${entryId}/override${qs({ unitId, reason })}`,
  },

  brokerage: {
    getDeals: (query?: M.ListQueryDto, status?: E.DealStatus, agentId?: string) => `${BASE}/brokerage/deals${qs({ query, status, agentId })}`,
    getBoard: (query?: M.ListQueryDto, agentId?: string) => `${BASE}/brokerage/deals/board${qs({ query, agentId })}`,
    getDeal: (id: string) => `${BASE}/brokerage/deals/${id}`,
    createDeal: `${BASE}/brokerage/deals`,
    updateChecklist: (dealId: string, itemId: string, completed?: boolean, completedOn?: string, note?: string) => `${BASE}/brokerage/deals/${dealId}/checklist/${itemId}${qs({ completed, completedOn, note })}`,
    changeDealStatus: (id: string, status?: E.DealStatus) => `${BASE}/brokerage/deals/${id}/status${qs({ status })}`,
    recordFallThrough: `${BASE}/brokerage/deals/fall-through`,
    saveDealParty: (dealId: string) => `${BASE}/brokerage/deals/${dealId}/parties`,
    saveChain: `${BASE}/brokerage/chains`,
    getChains: (atRiskOnly?: boolean) => `${BASE}/brokerage/chains${qs({ atRiskOnly })}`,
    saveConveyancing: `${BASE}/brokerage/conveyancing`,
    getPlans: (appliesTo?: string, projectId?: string) => `${BASE}/brokerage/commission-plans${qs({ appliesTo, projectId })}`,
    savePlan: `${BASE}/brokerage/commission-plans`,
    calculate: (dealId?: string, bookingId?: string, tenancyId?: string, commit?: boolean) => `${BASE}/brokerage/commission/calculate${qs({ dealId, bookingId, tenancyId, commit })}`,
    getCalculations: (query?: M.ListQueryDto, status?: E.CommissionStatus) => `${BASE}/brokerage/commission/calculations${qs({ query, status })}`,
    createDisbursement: (calculationId: string) => `${BASE}/brokerage/commission/${calculationId}/disburse`,
    decideDisbursement: (id: string, outcome?: E.ApprovalOutcome, comment?: string) => `${BASE}/brokerage/commission/disbursements/${id}/decide${qs({ outcome, comment })}`,
    createPayout: (agentId?: string, partnerId?: string, from?: string, to?: string) => `${BASE}/brokerage/commission/payouts${qs({ agentId, partnerId, from, to })}`,
    getPayouts: (query?: M.ListQueryDto) => `${BASE}/brokerage/commission/payouts${qs({ query })}`,
    getCapPosition: (agentId: string, year?: number) => `${BASE}/brokerage/commission/cap/${agentId}${qs({ year })}`,
    clawBack: (bookingId: string) => `${BASE}/brokerage/commission/clawback/${bookingId}`,
    getPartners: (query?: M.ListQueryDto, status?: E.PartnerStatus) => `${BASE}/brokerage/partners${qs({ query, status })}`,
    getPartner: (id: string) => `${BASE}/brokerage/partners/${id}`,
    savePartner: `${BASE}/brokerage/partners`,
    changePartnerStatus: (id: string, status?: E.PartnerStatus, reason?: string) => `${BASE}/brokerage/partners/${id}/status${qs({ status, reason })}`,
    getTiers: `${BASE}/brokerage/partners/tiers`,
    saveTier: `${BASE}/brokerage/partners/tiers`,
    getPartnerRates: (partnerId?: string, projectId?: string) => `${BASE}/brokerage/partners/rates${qs({ partnerId, projectId })}`,
    savePartnerRate: `${BASE}/brokerage/partners/rates`,
    registerLead: `${BASE}/brokerage/partners/registrations`,
    getRegistrations: (query?: M.ListQueryDto, partnerId?: string, status?: E.LeadRegistrationStatus) => `${BASE}/brokerage/partners/registrations${qs({ query, partnerId, status })}`,
    extendRegistration: (id: string, days?: number) => `${BASE}/brokerage/partners/registrations/${id}/extend${qs({ days })}`,
    expireRegistrations: `${BASE}/brokerage/partners/registrations/expire`,
    getPartnerCommission: (query?: M.ListQueryDto, partnerId?: string, status?: E.CommissionStatus) => `${BASE}/brokerage/partners/commission${qs({ query, partnerId, status })}`,
    generateStatement: (id: string, from?: string, to?: string) => `${BASE}/brokerage/partners/${id}/statement${qs({ from, to })}`,
    createAdvance: `${BASE}/brokerage/partners/advances`,
    getContests: (activeOnly?: boolean) => `${BASE}/brokerage/partners/contests${qs({ activeOnly })}`,
    saveContest: `${BASE}/brokerage/partners/contests`,
    getPartnerPortal: (id: string) => `${BASE}/brokerage/partners/${id}/portal`,
  },

  communication: {
    getConversations: (query?: M.ListQueryDto, channel?: E.NotificationChannel, status?: string, assignedToUserId?: string) => `${BASE}/communication/conversations${qs({ query, channel, status, assignedToUserId })}`,
    getConversation: (id: string) => `${BASE}/communication/conversations/${id}`,
    send: `${BASE}/communication/send`,
    assign: (id: string, assignToUserId?: string) => `${BASE}/communication/conversations/${id}/assign${qs({ assignToUserId })}`,
    close: (id: string) => `${BASE}/communication/conversations/${id}/close`,
    getTemplates: (channel?: E.NotificationChannel, category?: string) => `${BASE}/communication/templates${qs({ channel, category })}`,
    saveTemplate: `${BASE}/communication/templates`,
    runBroadcast: `${BASE}/communication/broadcasts`,
    getBroadcasts: (query?: M.ListQueryDto) => `${BASE}/communication/broadcasts${qs({ query })}`,
    getRules: `${BASE}/communication/rules`,
    saveRule: `${BASE}/communication/rules`,
    getNotifications: (query?: M.ListQueryDto, unreadOnly?: boolean) => `${BASE}/communication/notifications${qs({ query, unreadOnly })}`,
    markRead: `${BASE}/communication/notifications/read`,
    runAlertSweep: `${BASE}/communication/alerts/sweep`,
    getPortalUsers: (query?: M.ListQueryDto, audience?: E.PortalAudience) => `${BASE}/communication/portal-users${qs({ query, audience })}`,
    savePortalUser: `${BASE}/communication/portal-users`,
    invitePortalUser: (id: string) => `${BASE}/communication/portal-users/${id}/invite`,
    getCustomerPortal: (partyId: string) => `${BASE}/communication/portal/customer/${partyId}`,
  },

  construction: {
    getProjects: (query?: M.ListQueryDto, status?: E.ProjectStatus) => `${BASE}/construction/projects${qs({ query, status })}`,
    getProject: (id: string) => `${BASE}/construction/projects/${id}`,
    saveProject: `${BASE}/construction/projects`,
    getWbs: (id: string) => `${BASE}/construction/projects/${id}/wbs`,
    saveWbsNode: `${BASE}/construction/wbs`,
    deleteWbsNode: (id: string) => `${BASE}/construction/wbs/${id}`,
    getBoqs: (id: string) => `${BASE}/construction/projects/${id}/boqs`,
    getBoq: (id: string) => `${BASE}/construction/boqs/${id}`,
    saveBoq: `${BASE}/construction/boqs`,
    saveBoqLine: `${BASE}/construction/boqs/lines`,
    importBoqLines: (id: string) => `${BASE}/construction/boqs/${id}/import`,
    getRateAnalyses: (constructionProjectId?: string, libraryOnly?: boolean) => `${BASE}/construction/rate-analyses${qs({ constructionProjectId, libraryOnly })}`,
    saveRateAnalysis: `${BASE}/construction/rate-analyses`,
    getEstimates: (query?: M.ListQueryDto) => `${BASE}/construction/estimates${qs({ query })}`,
    saveEstimate: `${BASE}/construction/estimates`,
    convertEstimate: (id: string, constructionProjectId?: string) => `${BASE}/construction/estimates/${id}/to-boq${qs({ constructionProjectId })}`,
    getSpecifications: (constructionProjectId?: string, clientBuildContractId?: string) => `${BASE}/construction/specifications${qs({ constructionProjectId, clientBuildContractId })}`,
    saveSpecification: `${BASE}/construction/specifications`,
    freezeSpecification: (id: string) => `${BASE}/construction/specifications/${id}/freeze`,
    getProgramme: (id: string) => `${BASE}/construction/projects/${id}/programme`,
    saveActivity: (id: string) => `${BASE}/construction/projects/${id}/programme`,
    recalculateCriticalPath: (id: string) => `${BASE}/construction/projects/${id}/programme/critical-path`,
    baseline: (id: string) => `${BASE}/construction/projects/${id}/programme/baseline`,
    saveProgress: `${BASE}/construction/progress`,
    syncProgress: `${BASE}/construction/progress/sync`,
    certifyProgress: (id: string) => `${BASE}/construction/progress/${id}/certify`,
    getProgress: (query?: M.ListQueryDto, constructionProjectId?: string, subcontractId?: string) => `${BASE}/construction/progress${qs({ query, constructionProjectId, subcontractId })}`,
    prepareIpc: `${BASE}/construction/ipcs`,
    certifyIpc: (id: string) => `${BASE}/construction/ipcs/${id}/certify`,
    approveIpc: (id: string, outcome?: E.ApprovalOutcome, comment?: string) => `${BASE}/construction/ipcs/${id}/approve${qs({ outcome, comment })}`,
    getIpcs: (query?: M.ListQueryDto, constructionProjectId?: string, direction?: string, status?: E.CertificateStatus) => `${BASE}/construction/ipcs${qs({ query, constructionProjectId, direction, status })}`,
    getIpc: (id: string) => `${BASE}/construction/ipcs/${id}`,
    getRetention: (query?: M.ListQueryDto, subcontractId?: string, dueForReleaseOnly?: boolean) => `${BASE}/construction/retention${qs({ query, subcontractId, dueForReleaseOnly })}`,
    releaseRetention: (subcontractId?: string, clientBuildContractId?: string, amount?: number, movement?: E.RetentionMovement) => `${BASE}/construction/retention/release${qs({ subcontractId, clientBuildContractId, amount, movement })}`,
    createAdvance: `${BASE}/construction/advances`,
    saveMaterialsOnSite: `${BASE}/construction/materials-on-site`,
    recalculateCostToComplete: (id: string, asOf?: string) => `${BASE}/construction/projects/${id}/cost-to-complete${qs({ asOf })}`,
    getTenders: (query?: M.ListQueryDto, status?: E.TenderStatus) => `${BASE}/construction/tenders${qs({ query, status })}`,
    getTender: (id: string) => `${BASE}/construction/tenders/${id}`,
    saveTender: `${BASE}/construction/tenders`,
    submitBid: (id: string) => `${BASE}/construction/tenders/${id}/bids`,
    awardTender: (id: string, bidId?: string, justification?: string) => `${BASE}/construction/tenders/${id}/award${qs({ bidId, justification })}`,
    getBidComparison: (id: string) => `${BASE}/construction/tenders/${id}/comparison`,
    getSubcontracts: (query?: M.ListQueryDto, constructionProjectId?: string, status?: E.SubcontractStatus) => `${BASE}/construction/subcontracts${qs({ query, constructionProjectId, status })}`,
    getSubcontract: (id: string) => `${BASE}/construction/subcontracts/${id}`,
    saveSubcontract: `${BASE}/construction/subcontracts`,
    changeSubcontractStatus: (id: string, status?: E.SubcontractStatus, reason?: string) => `${BASE}/construction/subcontracts/${id}/status${qs({ status, reason })}`,
    submitClaim: `${BASE}/construction/claims`,
    certifyClaim: (id: string) => `${BASE}/construction/claims/${id}/certify`,
    getClaims: (query?: M.ListQueryDto, subcontractId?: string, status?: E.CertificateStatus) => `${BASE}/construction/claims${qs({ query, subcontractId, status })}`,
    saveContraCharge: `${BASE}/construction/contra-charges`,
    getVariations: (query?: M.ListQueryDto, constructionProjectId?: string, status?: E.VariationStatus) => `${BASE}/construction/variations${qs({ query, constructionProjectId, status })}`,
    getVariation: (id: string) => `${BASE}/construction/variations/${id}`,
    saveVariation: `${BASE}/construction/variations`,
    decideVariation: (id: string, status?: E.VariationStatus, reason?: string) => `${BASE}/construction/variations/${id}/decide${qs({ status, reason })}`,
    issueSiteInstruction: `${BASE}/construction/site-instructions`,
    getSiteInstructions: (query?: M.ListQueryDto, constructionProjectId?: string) => `${BASE}/construction/site-instructions${qs({ query, constructionProjectId })}`,
    saveDelay: `${BASE}/construction/delays`,
    getDelays: (query?: M.ListQueryDto, constructionProjectId?: string) => `${BASE}/construction/delays${qs({ query, constructionProjectId })}`,
    saveExtension: `${BASE}/construction/extensions`,
    decideExtension: (id: string, daysGranted?: number, prolongationGranted?: boolean, note?: string) => `${BASE}/construction/extensions/${id}/decide${qs({ daysGranted, prolongationGranted, note })}`,
    saveRequisition: `${BASE}/construction/requisitions`,
    approveRequisition: (id: string, outcome?: E.ApprovalOutcome, comment?: string) => `${BASE}/construction/requisitions/${id}/approve${qs({ outcome, comment })}`,
    getRequisitions: (query?: M.ListQueryDto, constructionProjectId?: string, status?: string) => `${BASE}/construction/requisitions${qs({ query, constructionProjectId, status })}`,
    issueMaterial: `${BASE}/construction/material-issues`,
    getIssues: (query?: M.ListQueryDto, constructionProjectId?: string) => `${BASE}/construction/material-issues${qs({ query, constructionProjectId })}`,
    calculateWastage: (id: string, from?: string, to?: string) => `${BASE}/construction/projects/${id}/wastage${qs({ from, to })}`,
    saveLabour: `${BASE}/construction/labour`,
    getLabour: (query?: M.ListQueryDto, constructionProjectId?: string) => `${BASE}/construction/labour${qs({ query, constructionProjectId })}`,
    getPlant: (status?: string) => `${BASE}/construction/plant${qs({ status })}`,
    savePlant: `${BASE}/construction/plant`,
    allocatePlant: `${BASE}/construction/plant/allocate`,
    recordSiteGateEntry: `${BASE}/construction/site-gate`,
    saveSafetyIncident: `${BASE}/construction/safety-incidents`,
    getSafetyIncidents: (query?: M.ListQueryDto, constructionProjectId?: string) => `${BASE}/construction/safety-incidents${qs({ query, constructionProjectId })}`,
    getClientBuilds: (query?: M.ListQueryDto, status?: string) => `${BASE}/construction/client-builds${qs({ query, status })}`,
    getClientBuild: (id: string) => `${BASE}/construction/client-builds/${id}`,
    saveClientBuild: `${BASE}/construction/client-builds`,
    changeClientBuildStatus: (id: string, status?: string) => `${BASE}/construction/client-builds/${id}/status${qs({ status })}`,
    saveClientVariation: `${BASE}/construction/client-builds/variations`,
    decideClientVariation: (id: string, approved?: boolean, reason?: string, evidenceUrl?: string) => `${BASE}/construction/client-builds/variations/${id}/decide${qs({ approved, reason, evidenceUrl })}`,
    getClientVariations: (query?: M.ListQueryDto, contractId?: string, status?: E.VariationStatus) => `${BASE}/construction/client-builds/variations${qs({ query, contractId, status })}`,
    getCostSheet: (id: string, asOf?: string) => `${BASE}/construction/client-builds/${id}/cost-sheet${qs({ asOf })}`,
    recalculateCostSheet: (id: string) => `${BASE}/construction/client-builds/${id}/cost-sheet`,
    getDrawings: (clientBuildContractId?: string, constructionProjectId?: string) => `${BASE}/construction/drawings${qs({ clientBuildContractId, constructionProjectId })}`,
    saveDrawing: `${BASE}/construction/drawings`,
    addRevision: (id: string) => `${BASE}/construction/drawings/${id}/revisions`,
    getClientPortal: (partyId: string) => `${BASE}/construction/client-builds/portal/${partyId}`,
  },

  crm: {
    searchParties: `${BASE}/crm/parties/search`,
    getParty: (id: string) => `${BASE}/crm/parties/${id}`,
    saveParty: `${BASE}/crm/parties`,
    lookupParties: (search?: string, role?: E.PartyRoleKind, take?: number) => `${BASE}/crm/parties/lookup${qs({ search, role, take })}`,
    findDuplicates: `${BASE}/crm/parties/duplicates`,
    mergeParties: (keepId?: string, mergeId?: string) => `${BASE}/crm/parties/merge${qs({ keepId, mergeId })}`,
    getKyc: (partyId: string) => `${BASE}/crm/parties/${partyId}/kyc`,
    saveKyc: `${BASE}/crm/kyc`,
    decideKyc: (id: string, status?: E.KycStatus, note?: string) => `${BASE}/crm/kyc/${id}/decide${qs({ status, note })}`,
    getKycQueue: (query?: M.ListQueryDto, status?: E.KycStatus) => `${BASE}/crm/kyc/queue${qs({ query, status })}`,
    getCautionList: (query?: M.ListQueryDto) => `${BASE}/crm/caution-list${qs({ query })}`,
    addCaution: `${BASE}/crm/caution-list`,
    clearCaution: (id: string, note?: string) => `${BASE}/crm/caution-list/${id}/clear${qs({ note })}`,
    searchEnquiries: `${BASE}/crm/enquiries/search`,
    getBoard: `${BASE}/crm/enquiries/board`,
    getEnquiry: (id: string) => `${BASE}/crm/enquiries/${id}`,
    saveEnquiry: `${BASE}/crm/enquiries`,
    changeStage: `${BASE}/crm/enquiries/stage`,
    assign: (id: string, agentId?: string) => `${BASE}/crm/enquiries/${id}/assign${qs({ agentId })}`,
    route: `${BASE}/crm/enquiries/route`,
    flagSla: `${BASE}/crm/enquiries/flag-sla`,
    saveRequirement: `${BASE}/crm/requirements`,
    getRequirements: (partyId: string) => `${BASE}/crm/parties/${partyId}/requirements`,
    runMatch: (id: string, take?: number) => `${BASE}/crm/requirements/${id}/matches${qs({ take })}`,
    matchListing: (listingId: string, take?: number) => `${BASE}/crm/listings/${listingId}/matches${qs({ take })}`,
    sendMatches: `${BASE}/crm/matches/send`,
    dismissMatch: (matchId: string, reasonCodeId?: string) => `${BASE}/crm/matches/${matchId}/dismiss${qs({ reasonCodeId })}`,
    logActivity: `${BASE}/crm/activities`,
    getActivities: (partyId?: string, enquiryId?: string, query?: M.ListQueryDto) => `${BASE}/crm/activities${qs({ partyId, enquiryId, query })}`,
    saveTask: `${BASE}/crm/tasks`,
    completeTask: `${BASE}/crm/tasks/complete`,
    snoozeTask: (taskId: string, until?: string) => `${BASE}/crm/tasks/${taskId}/snooze${qs({ until })}`,
    getMyDay: (date?: string) => `${BASE}/crm/my-day${qs({ date })}`,
    getDiary: (agentId?: string, date?: string) => `${BASE}/crm/diary${qs({ agentId, date })}`,
    getViewings: (query?: M.ListQueryDto, agentId?: string, status?: E.ViewingStatus) => `${BASE}/crm/viewings${qs({ query, agentId, status })}`,
    getViewing: (id: string) => `${BASE}/crm/viewings/${id}`,
    saveViewing: `${BASE}/crm/viewings`,
    changeViewingStatus: (id: string, status?: E.ViewingStatus, reasonCodeId?: string, note?: string) => `${BASE}/crm/viewings/${id}/status${qs({ status, reasonCodeId, note })}`,
    saveFeedback: `${BASE}/crm/viewings/feedback`,
    shareFeedback: (feedbackId: string) => `${BASE}/crm/viewings/feedback/${feedbackId}/share`,
    getSiteVisits: (query?: M.ListQueryDto, projectId?: string, status?: E.ViewingStatus) => `${BASE}/crm/site-visits${qs({ query, projectId, status })}`,
    getSiteVisit: (id: string) => `${BASE}/crm/site-visits/${id}`,
    saveSiteVisit: `${BASE}/crm/site-visits`,
    changeVisitStatus: (id: string, status?: E.ViewingStatus, reasonCodeId?: string) => `${BASE}/crm/site-visits/${id}/status${qs({ status, reasonCodeId })}`,
    saveVisitFeedback: `${BASE}/crm/site-visits/feedback`,
    getKeys: (propertyId?: string, outOnly?: boolean) => `${BASE}/crm/keys${qs({ propertyId, outOnly })}`,
    saveKeySet: `${BASE}/crm/keys`,
    moveKeys: (keySetId: string, movement?: string, holderUserId?: string, holderPartyId?: string, dueBack?: string, note?: string) => `${BASE}/crm/keys/${keySetId}/move${qs({ movement, holderUserId, holderPartyId, dueBack, note })}`,
  },

  exit: {
    previewCancellation: `${BASE}/exit/cancellations/preview`,
    requestCancellation: `${BASE}/exit/cancellations`,
    decideCancellation: (id: string, outcome?: E.ApprovalOutcome, comment?: string) => `${BASE}/exit/cancellations/${id}/decide${qs({ outcome, comment })}`,
    getCancellations: (query?: M.ListQueryDto) => `${BASE}/exit/cancellations${qs({ query })}`,
    getDeductionPolicies: (projectId?: string) => `${BASE}/exit/deduction-policies${qs({ projectId })}`,
    saveDeductionPolicy: `${BASE}/exit/deduction-policies`,
    createRefund: `${BASE}/exit/refunds`,
    decideRefund: (id: string, outcome?: E.ApprovalOutcome, approvedAmount?: number, comment?: string) => `${BASE}/exit/refunds/${id}/decide${qs({ outcome, approvedAmount, comment })}`,
    recordRefundPayment: (scheduleId: string, paidOn?: string, instrument?: E.PaymentInstrument, reference?: string) => `${BASE}/exit/refunds/schedule/${scheduleId}/pay${qs({ paidOn, instrument, reference })}`,
    getRefunds: (query?: M.ListQueryDto, status?: E.RefundStatus) => `${BASE}/exit/refunds${qs({ query, status })}`,
    createResale: `${BASE}/exit/resales`,
    getTransfers: (query?: M.ListQueryDto, status?: E.TransferStatus, projectId?: string) => `${BASE}/exit/transfers${qs({ query, status, projectId })}`,
    getTransfer: (id: string) => `${BASE}/exit/transfers/${id}`,
    createTransfer: `${BASE}/exit/transfers`,
    issueDuesClearance: (bookingId?: string, unitId?: string, propertyId?: string, partyId?: string) => `${BASE}/exit/dues-clearance${qs({ bookingId, unitId, propertyId, partyId })}`,
    overrideDues: (id: string, reason?: string) => `${BASE}/exit/transfers/${id}/override-dues${qs({ reason })}`,
    computeFees: (id: string) => `${BASE}/exit/transfers/${id}/fees`,
    scheduleSession: (id: string, scheduledAt?: string, venue?: string) => `${BASE}/exit/transfers/${id}/session${qs({ scheduledAt, venue })}`,
    saveSession: `${BASE}/exit/transfers/session`,
    completeTransfer: (id: string) => `${BASE}/exit/transfers/${id}/complete`,
    rejectTransfer: (id: string, reasonCodeId?: string, note?: string) => `${BASE}/exit/transfers/${id}/reject${qs({ reasonCodeId, note })}`,
    getOwnershipChain: (unitId?: string, propertyId?: string, plotFileId?: string) => `${BASE}/exit/ownership-chain${qs({ unitId, propertyId, plotFileId })}`,
    createDuplicateFileRequest: `${BASE}/exit/duplicate-files`,
    issueDuplicateFile: (id: string) => `${BASE}/exit/duplicate-files/${id}/issue`,
    evaluatePossession: (bookingId: string) => `${BASE}/exit/possession/${bookingId}/evaluate`,
    offerPossession: (bookingId: string, windowFrom?: string, windowTo?: string, templateId?: string) => `${BASE}/exit/possession/${bookingId}/offer${qs({ windowFrom, windowTo, templateId })}`,
    setAppointment: (id: string, on?: string) => `${BASE}/exit/possession/${id}/appointment${qs({ on })}`,
    overrideChecklist: (checklistItemId: string, reason?: string) => `${BASE}/exit/possession/checklist/${checklistItemId}/override${qs({ reason })}`,
    getPossessions: (query?: M.ListQueryDto, status?: E.PossessionStatus, projectId?: string) => `${BASE}/exit/possession${qs({ query, status, projectId })}`,
    completeHandover: `${BASE}/exit/handovers`,
    getHandover: (id: string) => `${BASE}/exit/handovers/${id}`,
    createInspection: `${BASE}/exit/inspections`,
    getInspection: (id: string) => `${BASE}/exit/inspections/${id}`,
    getInspections: (query?: M.ListQueryDto, projectId?: string, openOnly?: boolean) => `${BASE}/exit/inspections${qs({ query, projectId, openOnly })}`,
    saveSnag: `${BASE}/exit/snags`,
    syncSnags: `${BASE}/exit/snags/sync`,
    changeSnagStatus: (id: string, status?: E.SnagStatus, note?: string) => `${BASE}/exit/snags/${id}/status${qs({ status, note })}`,
    issuePunchList: (id: string, agreedClosureDate?: string) => `${BASE}/exit/inspections/${id}/punch-list${qs({ agreedClosureDate })}`,
    getLiabilities: (unitId?: string, projectId?: string, activeOnly?: boolean) => `${BASE}/exit/defect-liabilities${qs({ unitId, projectId, activeOnly })}`,
    createDefectClaim: `${BASE}/exit/defect-claims`,
    decideDefectClaim: (id: string, accepted?: boolean, reason?: string) => `${BASE}/exit/defect-claims/${id}/decide${qs({ accepted, reason })}`,
    getDefectClaims: (query?: M.ListQueryDto, status?: E.TicketStatus) => `${BASE}/exit/defect-claims${qs({ query, status })}`,
    requestNoc: `${BASE}/exit/nocs`,
    issueNoc: (id: string) => `${BASE}/exit/nocs/${id}/issue`,
    revokeNoc: (id: string, reason?: string) => `${BASE}/exit/nocs/${id}/revoke${qs({ reason })}`,
    getNocs: (query?: M.ListQueryDto, kind?: E.NocKind, status?: E.NocStatus) => `${BASE}/exit/nocs${qs({ query, kind, status })}`,
    verifyNoc: (code: string) => `${BASE}/exit/nocs/verify/${code}`,
  },

  facility: {
    searchWorkOrders: `${BASE}/facility/work-orders/search`,
    getWorkOrder: (id: string) => `${BASE}/facility/work-orders/${id}`,
    createWorkOrder: `${BASE}/facility/work-orders`,
    assignWorkOrder: (id: string, assignToUserId?: string, contractorId?: string, from?: string, to?: string) => `${BASE}/facility/work-orders/${id}/assign${qs({ assignToUserId, contractorId, from, to })}`,
    authoriseWorkOrder: (id: string, outcome?: E.ApprovalOutcome, comment?: string) => `${BASE}/facility/work-orders/${id}/authorise${qs({ outcome, comment })}`,
    completeWorkOrder: `${BASE}/facility/work-orders/complete`,
    cancelWorkOrder: (id: string, reasonCodeId?: string) => `${BASE}/facility/work-orders/${id}/cancel${qs({ reasonCodeId })}`,
    flagSla: `${BASE}/facility/work-orders/flag-sla`,
    getContractors: (query?: M.ListQueryDto, trade?: string, approvedOnly?: boolean) => `${BASE}/facility/contractors${qs({ query, trade, approvedOnly })}`,
    getContractor: (id: string) => `${BASE}/facility/contractors/${id}`,
    saveContractor: `${BASE}/facility/contractors`,
    saveCompliance: (id: string) => `${BASE}/facility/contractors/${id}/compliance`,
    getPpmSchedules: (query?: M.ListQueryDto, propertyId?: string, overdueOnly?: boolean) => `${BASE}/facility/ppm/schedules${qs({ query, propertyId, overdueOnly })}`,
    savePpmSchedule: `${BASE}/facility/ppm/schedules`,
    getPpmTasks: (query?: M.ListQueryDto, status?: string) => `${BASE}/facility/ppm/tasks${qs({ query, status })}`,
    generatePpm: (asOf?: string) => `${BASE}/facility/ppm/generate${qs({ asOf })}`,
    completePpmTask: (id: string, completedOn?: string, cost?: number, note?: string, certificateUrl?: string) => `${BASE}/facility/ppm/tasks/${id}/complete${qs({ completedOn, cost, note, certificateUrl })}`,
    getAssets: (query?: M.ListQueryDto, propertyId?: string, kind?: E.AssetKind) => `${BASE}/facility/assets${qs({ query, propertyId, kind })}`,
    getAsset: (id: string) => `${BASE}/facility/assets/${id}`,
    saveAsset: `${BASE}/facility/assets`,
    recordService: (id: string) => `${BASE}/facility/assets/${id}/service`,
    getServiceContracts: (propertyId?: string, expiringOnly?: boolean) => `${BASE}/facility/service-contracts${qs({ propertyId, expiringOnly })}`,
    saveServiceContract: `${BASE}/facility/service-contracts`,
    saveInspectionRound: `${BASE}/facility/inspection-rounds`,
    getInspectionRounds: (query?: M.ListQueryDto, propertyId?: string) => `${BASE}/facility/inspection-rounds${qs({ query, propertyId })}`,
    getMeters: (query?: M.ListQueryDto, propertyId?: string, societyId?: string, kind?: E.MeterKind) => `${BASE}/facility/meters${qs({ query, propertyId, societyId, kind })}`,
    saveMeter: `${BASE}/facility/meters`,
    getReadingRound: (societyId?: string, propertyId?: string, kind?: E.MeterKind) => `${BASE}/facility/meters/round${qs({ societyId, propertyId, kind })}`,
    submitReadings: `${BASE}/facility/meters/readings`,
    getReadings: (query?: M.ListQueryDto, meterId?: string, implausibleOnly?: boolean) => `${BASE}/facility/meters/readings${qs({ query, meterId, implausibleOnly })}`,
    verifyReading: (id: string, correctedValue?: number) => `${BASE}/facility/meters/readings/${id}/verify${qs({ correctedValue })}`,
    getTariffs: (societyId?: string, kind?: E.MeterKind) => `${BASE}/facility/tariffs${qs({ societyId, kind })}`,
    saveTariff: `${BASE}/facility/tariffs`,
    generateUtilityBills: (societyId?: string, periodFrom?: string, periodTo?: string, dryRun?: boolean) => `${BASE}/facility/utility-bills/generate${qs({ societyId, periodFrom, periodTo, dryRun })}`,
    getUtilityBills: (query?: M.ListQueryDto, unitId?: string) => `${BASE}/facility/utility-bills${qs({ query, unitId })}`,
    reconcileUtility: (societyId?: string, propertyId?: string, kind?: E.MeterKind, from?: string, to?: string) => `${BASE}/facility/utility-bills/reconcile${qs({ societyId, propertyId, kind, from, to })}`,
    saveFuelLog: `${BASE}/facility/fuel-logs`,
    getFuelLogs: (query?: M.ListQueryDto, societyId?: string) => `${BASE}/facility/fuel-logs${qs({ query, societyId })}`,
    getParking: (query?: M.ListQueryDto, societyId?: string, unallottedOnly?: boolean) => `${BASE}/facility/parking${qs({ query, societyId, unallottedOnly })}`,
    saveParkingSlot: `${BASE}/facility/parking`,
    allotParking: `${BASE}/facility/parking/allot`,
  },

  finance: {
    getVentures: (projectId?: string) => `${BASE}/finance/ventures${qs({ projectId })}`,
    getVenture: (id: string) => `${BASE}/finance/ventures/${id}`,
    saveVenture: `${BASE}/finance/ventures`,
    allocateUnit: (id: string, unitId?: string, jvPartnerId?: string) => `${BASE}/finance/ventures/${id}/allocate${qs({ unitId, jvPartnerId })}`,
    releaseAllocation: (id: string) => `${BASE}/finance/ventures/allocations/${id}/release`,
    getLandownerLedger: (id: string, query?: M.ListQueryDto) => `${BASE}/finance/ventures/${id}/ledger${qs({ query })}`,
    accrueLandownerShare: (id: string) => `${BASE}/finance/ventures/${id}/accrue`,
    getInvestors: (query?: M.ListQueryDto, projectId?: string) => `${BASE}/finance/investors${qs({ query, projectId })}`,
    getInvestor: (id: string) => `${BASE}/finance/investors/${id}`,
    saveInvestor: `${BASE}/finance/investors`,
    issueCapitalCall: `${BASE}/finance/capital-calls`,
    recordContribution: `${BASE}/finance/contributions`,
    recordDistribution: `${BASE}/finance/distributions`,
    getProjectAccounts: (projectId: string) => `${BASE}/finance/projects/${projectId}/accounts`,
    saveProjectAccount: `${BASE}/finance/accounts`,
    getEscrowLedger: (id: string, query?: M.ListQueryDto) => `${BASE}/finance/accounts/${id}/ledger${qs({ query })}`,
    requestWithdrawal: `${BASE}/finance/escrow/withdrawals`,
    decideWithdrawal: (id: string, outcome?: E.ApprovalOutcome, approvedAmount?: number, comment?: string) => `${BASE}/finance/escrow/withdrawals/${id}/decide${qs({ outcome, approvedAmount, comment })}`,
    getWithdrawals: (query?: M.ListQueryDto, projectId?: string) => `${BASE}/finance/escrow/withdrawals${qs({ query, projectId })}`,
    recomputeEntitlement: (id: string) => `${BASE}/finance/accounts/${id}/recompute-entitlement`,
    getLoans: (query?: M.ListQueryDto, projectId?: string) => `${BASE}/finance/loans${qs({ query, projectId })}`,
    saveLoan: `${BASE}/finance/loans`,
    recordDrawdown: (id: string) => `${BASE}/finance/loans/${id}/drawdowns`,
    getGuarantees: (projectId?: string, expiringOnly?: boolean) => `${BASE}/finance/guarantees${qs({ projectId, expiringOnly })}`,
    saveGuarantee: `${BASE}/finance/guarantees`,
    getMortgages: (query?: M.ListQueryDto, status?: string) => `${BASE}/finance/mortgages${qs({ query, status })}`,
    saveMortgage: `${BASE}/finance/mortgages`,
    recordDisbursement: (id: string) => `${BASE}/finance/mortgages/${id}/disbursements`,
    saveRecognitionPolicy: `${BASE}/finance/recognition/policies`,
    runRecognition: (projectId?: string, periodFrom?: string, periodTo?: string, dryRun?: boolean) => `${BASE}/finance/recognition/run${qs({ projectId, periodFrom, periodTo, dryRun })}`,
    getRecognitionRuns: (query?: M.ListQueryDto) => `${BASE}/finance/recognition/runs${qs({ query })}`,
    getWip: (projectId: string, query?: M.ListQueryDto) => `${BASE}/finance/projects/${projectId}/wip${qs({ query })}`,
    getUnitProfitability: (projectId: string, query?: M.ListQueryDto) => `${BASE}/finance/projects/${projectId}/profitability${qs({ query })}`,
    allocateCosts: (projectId: string, asOf?: string) => `${BASE}/finance/projects/${projectId}/allocate-costs${qs({ asOf })}`,
    getProjectPnl: (projectId: string, asOf?: string) => `${BASE}/finance/projects/${projectId}/pnl${qs({ asOf })}`,
    getTaxProfiles: (projectId?: string) => `${BASE}/finance/tax-profiles${qs({ projectId })}`,
    saveTaxProfile: `${BASE}/finance/tax-profiles`,
    getWithholding: (query?: M.ListQueryDto, kind?: E.WithholdingKind, undepositedOnly?: boolean) => `${BASE}/finance/withholding${qs({ query, kind, undepositedOnly })}`,
    getApprovalRecords: (query?: M.ListQueryDto, projectId?: string, state?: E.ApprovalState) => `${BASE}/finance/approvals${qs({ query, projectId, state })}`,
    saveApprovalRecord: `${BASE}/finance/approvals`,
    getLicences: (expiringOnly?: boolean) => `${BASE}/finance/licences${qs({ expiringOnly })}`,
    saveLicence: `${BASE}/finance/licences`,
    getCalendar: (from?: string, to?: string, category?: string) => `${BASE}/finance/compliance-calendar${qs({ from, to, category })}`,
    completeCalendarEntry: (id: string, evidenceUrl?: string) => `${BASE}/finance/compliance-calendar/${id}/complete${qs({ evidenceUrl })}`,
    getFilings: (query?: M.ListQueryDto, status?: string) => `${BASE}/finance/filings${qs({ query, status })}`,
    generateQpr: (projectId?: string, year?: number, quarter?: number) => `${BASE}/finance/qpr${qs({ projectId, year, quarter })}`,
    fileQpr: (id: string, acknowledgementNumber?: string) => `${BASE}/finance/qpr/${id}/file${qs({ acknowledgementNumber })}`,
    getQpr: (id: string) => `${BASE}/finance/qpr/${id}`,
    getTemplates: (documentType?: string, projectId?: string) => `${BASE}/finance/templates${qs({ documentType, projectId })}`,
    saveTemplate: `${BASE}/finance/templates`,
    publishVersion: (id: string) => `${BASE}/finance/templates/${id}/versions`,
    getClauses: (category?: string, projectId?: string) => `${BASE}/finance/clauses${qs({ category, projectId })}`,
    saveClause: `${BASE}/finance/clauses`,
    generateDocument: `${BASE}/finance/documents/generate`,
    getDocuments: (query?: M.ListQueryDto, documentType?: string, entityId?: string) => `${BASE}/finance/documents${qs({ query, documentType, entityId })}`,
    verifyDocument: (code: string) => `${BASE}/finance/documents/verify/${code}`,
    startSigning: (id: string, method?: E.SignatureMethod, sequential?: boolean) => `${BASE}/finance/documents/${id}/sign${qs({ method, sequential })}`,
    recordSignature: (sessionId: string, partyId?: string, signatureUrl?: string, thumbUrl?: string, photoUrl?: string) => `${BASE}/finance/signing/${sessionId}/record${qs({ partyId, signatureUrl, thumbUrl, photoUrl })}`,
    getSigning: (id: string) => `${BASE}/finance/signing/${id}`,
    getPhysicalFiles: (query?: M.ListQueryDto, state?: E.PhysicalFileState) => `${BASE}/finance/files${qs({ query, state })}`,
    savePhysicalFile: `${BASE}/finance/files`,
    movePhysicalFile: (id: string, movement?: string, toUserId?: string, toName?: string, purpose?: string, dueBack?: string) => `${BASE}/finance/files/${id}/move${qs({ movement, toUserId, toName, purpose, dueBack })}`,
    getLegalCases: (query?: M.ListQueryDto, status?: E.LegalCaseStatus) => `${BASE}/finance/legal-cases${qs({ query, status })}`,
    getLegalCase: (id: string) => `${BASE}/finance/legal-cases/${id}`,
    saveLegalCase: `${BASE}/finance/legal-cases`,
    recordHearing: (id: string) => `${BASE}/finance/legal-cases/${id}/hearings`,
  },

  inventory: {
    getBoard: `${BASE}/inventory/board`,
    getUnit: (unitId: string) => `${BASE}/inventory/units/${unitId}`,
    saveUnit: `${BASE}/inventory/units`,
    hold: `${BASE}/inventory/holds`,
    releaseHold: (holdId: string, note?: string) => `${BASE}/inventory/holds/${holdId}/release${qs({ note })}`,
    getActiveHolds: (projectId?: string) => `${BASE}/inventory/holds${qs({ projectId })}`,
    expireHolds: `${BASE}/inventory/holds/expire`,
    block: `${BASE}/inventory/blocks`,
    unblock: (unitId: string, note?: string) => `${BASE}/inventory/units/${unitId}/unblock${qs({ note })}`,
    getPriceLists: (projectId?: string) => `${BASE}/inventory/price-lists${qs({ projectId })}`,
    getPriceList: (id: string) => `${BASE}/inventory/price-lists/${id}`,
    savePriceList: `${BASE}/inventory/price-lists`,
    publishPriceList: (id: string) => `${BASE}/inventory/price-lists/${id}/publish`,
    reprice: (id: string) => `${BASE}/inventory/price-lists/${id}/reprice`,
    getPremiums: (projectId?: string) => `${BASE}/inventory/premiums${qs({ projectId })}`,
    savePremium: `${BASE}/inventory/premiums`,
    getCostSheet: (unitId: string, paymentPlanTemplateId?: string, discountAmount?: number, discountPercent?: number) => `${BASE}/inventory/units/${unitId}/cost-sheet${qs({ paymentPlanTemplateId, discountAmount, discountPercent })}`,
  },

  leasing: {
    searchTenancies: `${BASE}/leasing/tenancies/search`,
    getTenancy: (id: string) => `${BASE}/leasing/tenancies/${id}`,
    createTenancy: `${BASE}/leasing/tenancies`,
    updateTenancy: (id: string) => `${BASE}/leasing/tenancies/${id}`,
    changeStatus: (id: string, status?: E.TenancyStatus) => `${BASE}/leasing/tenancies/${id}/status${qs({ status })}`,
    regenerateSchedule: (id: string) => `${BASE}/leasing/tenancies/${id}/schedule`,
    saveReferencing: `${BASE}/leasing/referencing`,
    decideReferencing: (id: string, outcome?: E.ReferencingOutcome, conditions?: string, failureReason?: string) => `${BASE}/leasing/referencing/${id}/decide${qs({ outcome, conditions, failureReason })}`,
    saveDeposit: `${BASE}/leasing/deposits`,
    registerDeposit: (id: string, schemeName?: string, reference?: string, registeredOn?: string) => `${BASE}/leasing/deposits/${id}/register${qs({ schemeName, reference, registeredOn })}`,
    proposeDeductions: (id: string) => `${BASE}/leasing/deposits/${id}/deductions`,
    releaseDeposit: (id: string, toTenant?: number, toLandlord?: number) => `${BASE}/leasing/deposits/${id}/release${qs({ toTenant, toLandlord })}`,
    getDeposits: (query?: M.ListQueryDto, unregisteredOnly?: boolean) => `${BASE}/leasing/deposits${qs({ query, unregisteredOnly })}`,
    saveInspection: `${BASE}/leasing/inspections`,
    getInspection: (id: string) => `${BASE}/leasing/inspections/${id}`,
    getInspections: (query?: M.ListQueryDto, kind?: E.InspectionKind) => `${BASE}/leasing/inspections${qs({ query, kind })}`,
    serveNotice: `${BASE}/leasing/notices`,
    offerRenewal: `${BASE}/leasing/renewals`,
    decideRenewal: (id: string, status?: string, agreedRent?: number, declineReasonCodeId?: string) => `${BASE}/leasing/renewals/${id}/decide${qs({ status, agreedRent, declineReasonCodeId })}`,
    getRenewalPipeline: (query?: M.ListQueryDto, withinDays?: number) => `${BASE}/leasing/renewals${qs({ query, withinDays })}`,
    saveRentReview: `${BASE}/leasing/rent-reviews`,
    getCriticalDates: (propertyId?: string, withinDays?: number) => `${BASE}/leasing/critical-dates${qs({ propertyId, withinDays })}`,
    actionCriticalDate: (id: string, note?: string) => `${BASE}/leasing/critical-dates/${id}/action${qs({ note })}`,
    getCertificates: (query?: M.ListQueryDto, expiringOnly?: boolean) => `${BASE}/leasing/certificates${qs({ query, expiringOnly })}`,
    saveCertificate: `${BASE}/leasing/certificates`,
    getRentRoll: (propertyId?: string, projectId?: string, asOf?: string) => `${BASE}/leasing/rent-roll${qs({ propertyId, projectId, asOf })}`,
    runRent: `${BASE}/leasing/rent-runs`,
    getRentRuns: (query?: M.ListQueryDto) => `${BASE}/leasing/rent-runs${qs({ query })}`,
    getArrears: (query?: M.ListQueryDto, minDays?: number) => `${BASE}/leasing/arrears${qs({ query, minDays })}`,
    getVoids: (propertyId?: string, openOnly?: boolean) => `${BASE}/leasing/voids${qs({ propertyId, openOnly })}`,
    getTenantMix: (propertyId: string) => `${BASE}/leasing/tenant-mix/${propertyId}`,
    getBudgets: (query?: M.ListQueryDto, propertyId?: string) => `${BASE}/leasing/service-charge/budgets${qs({ query, propertyId })}`,
    getBudget: (id: string) => `${BASE}/leasing/service-charge/budgets/${id}`,
    saveBudget: `${BASE}/leasing/service-charge/budgets`,
    approveBudget: (id: string) => `${BASE}/leasing/service-charge/budgets/${id}/approve`,
    raiseOnAccount: (id: string, periodFrom?: string, periodTo?: string, dryRun?: boolean) => `${BASE}/leasing/service-charge/budgets/${id}/on-account${qs({ periodFrom, periodTo, dryRun })}`,
    reconcile: (id: string, dryRun?: boolean) => `${BASE}/leasing/service-charge/budgets/${id}/reconcile${qs({ dryRun })}`,
    finaliseReconciliation: (id: string) => `${BASE}/leasing/service-charge/reconciliations/${id}/finalise`,
    getApportionments: (propertyId: string) => `${BASE}/leasing/service-charge/apportionments/${propertyId}`,
    saveApportionment: `${BASE}/leasing/service-charge/apportionments`,
    saveTurnoverTerm: `${BASE}/leasing/turnover/terms`,
    saveSalesDeclaration: `${BASE}/leasing/turnover/declarations`,
    getSalesDeclarations: (query?: M.ListQueryDto, propertyId?: string, overdueOnly?: boolean) => `${BASE}/leasing/turnover/declarations${qs({ query, propertyId, overdueOnly })}`,
    calculateOverage: (propertyId?: string, periodFrom?: string, periodTo?: string, dryRun?: boolean) => `${BASE}/leasing/turnover/overage${qs({ propertyId, periodFrom, periodTo, dryRun })}`,
    getLandlords: (query?: M.ListQueryDto) => `${BASE}/leasing/landlords${qs({ query })}`,
    getLandlord: (id: string) => `${BASE}/leasing/landlords/${id}`,
    saveLandlord: `${BASE}/leasing/landlords`,
    saveAgreement: (id: string) => `${BASE}/leasing/landlords/${id}/agreement`,
    generateStatement: (id: string, from?: string, to?: string, propertyId?: string) => `${BASE}/leasing/landlords/${id}/statement${qs({ from, to, propertyId })}`,
    getStatements: (query?: M.ListQueryDto, landlordId?: string) => `${BASE}/leasing/landlords/statements${qs({ query, landlordId })}`,
    createPayoutRun: (payoutDate?: string, officeId?: string, clientAccountId?: string, dryRun?: boolean) => `${BASE}/leasing/landlords/payouts${qs({ payoutDate, officeId, clientAccountId, dryRun })}`,
    submitPayoutRun: (id: string) => `${BASE}/leasing/landlords/payouts/${id}/submit`,
    getPayoutRuns: (query?: M.ListQueryDto) => `${BASE}/leasing/landlords/payouts${qs({ query })}`,
    getClientAccounts: `${BASE}/leasing/client-accounts`,
    saveClientAccount: `${BASE}/leasing/client-accounts`,
    getClientLedger: (id: string, query?: M.ListQueryDto) => `${BASE}/leasing/client-accounts/${id}/ledger${qs({ query })}`,
    reconcileClientMoney: (id: string, asOf?: string, bankBalance?: number) => `${BASE}/leasing/client-accounts/${id}/reconcile${qs({ asOf, bankBalance })}`,
    signOff: (id: string) => `${BASE}/leasing/client-money/reconciliations/${id}/sign-off`,
    getExceptions: (query?: M.ListQueryDto, openOnly?: boolean) => `${BASE}/leasing/client-money/exceptions${qs({ query, openOnly })}`,
    getOwnerPortal: (landlordId: string) => `${BASE}/leasing/portal/owner/${landlordId}`,
    getTenantPortal: (partyId: string) => `${BASE}/leasing/portal/tenant/${partyId}`,
  },

  listing: {
    search: `${BASE}/listings/search`,
    get: (id: string) => `${BASE}/listings/${id}`,
    save: `${BASE}/listings`,
    changeStatus: (id: string, status?: E.ListingStatus, reasonCodeId?: string) => `${BASE}/listings/${id}/status${qs({ status, reasonCodeId })}`,
    changePrice: `${BASE}/listings/price`,
    checkReadiness: (id: string) => `${BASE}/listings/${id}/publish-readiness`,
    getInstructions: (query?: M.ListQueryDto) => `${BASE}/listings/instructions${qs({ query })}`,
    getInstruction: (id: string) => `${BASE}/listings/instructions/${id}`,
    saveInstruction: `${BASE}/listings/instructions`,
    terminateInstruction: (id: string, reasonCodeId?: string, note?: string) => `${BASE}/listings/instructions/${id}/terminate${qs({ reasonCodeId, note })}`,
    getPortals: `${BASE}/listings/portals`,
    savePortal: `${BASE}/listings/portals`,
    getMappings: (portalId: string) => `${BASE}/listings/portals/${portalId}/mappings`,
    saveMapping: `${BASE}/listings/portals/mappings`,
    publish: `${BASE}/listings/publish`,
    getPublications: (query?: M.ListQueryDto, portalId?: string, state?: E.PortalPublishState) => `${BASE}/listings/publications${qs({ query, portalId, state })}`,
    getCampaigns: (query?: M.ListQueryDto) => `${BASE}/listings/campaigns${qs({ query })}`,
    saveCampaign: `${BASE}/listings/campaigns`,
    getEvents: (query?: M.ListQueryDto) => `${BASE}/listings/events${qs({ query })}`,
    saveEvent: `${BASE}/listings/events`,
    getContent: (query?: M.ListQueryDto) => `${BASE}/listings/content${qs({ query })}`,
    saveContent: `${BASE}/listings/content`,
  },

  money: {
    getTemplates: (projectId?: string, activeOnly?: boolean) => `${BASE}/money/plan-templates${qs({ projectId, activeOnly })}`,
    getTemplate: (id: string) => `${BASE}/money/plan-templates/${id}`,
    saveTemplate: `${BASE}/money/plan-templates`,
    previewPlan: (templateId?: string, totalConsideration?: number, startDate?: string, projectId?: string) => `${BASE}/money/plans/preview${qs({ templateId, totalConsideration, startDate, projectId })}`,
    getPlan: (bookingId: string) => `${BASE}/money/plans/${bookingId}`,
    restructure: `${BASE}/money/plans/restructure`,
    getSurchargePolicies: (projectId?: string) => `${BASE}/money/surcharge-policies${qs({ projectId })}`,
    saveSurchargePolicy: `${BASE}/money/surcharge-policies`,
    accrue: (asOf?: string) => `${BASE}/money/surcharge/accrue${qs({ asOf })}`,
    requestWaiver: `${BASE}/money/surcharge/waivers`,
    decideWaiver: (id: string, outcome?: E.ApprovalOutcome, approvedAmount?: number, comment?: string) => `${BASE}/money/surcharge/waivers/${id}/decide${qs({ outcome, approvedAmount, comment })}`,
    getWaivers: (query?: M.ListQueryDto, outcome?: E.ApprovalOutcome) => `${BASE}/money/surcharge/waivers${qs({ query, outcome })}`,
    runDemands: `${BASE}/money/demands/run`,
    getBatches: (query?: M.ListQueryDto) => `${BASE}/money/demand-batches${qs({ query })}`,
    getDemands: (query?: M.ListQueryDto, bookingId?: string, status?: E.DemandStatus) => `${BASE}/money/demands${qs({ query, bookingId, status })}`,
    getDemand: (id: string) => `${BASE}/money/demands/${id}`,
    sendDemand: (id: string) => `${BASE}/money/demands/${id}/send`,
    cancelDemand: (id: string, reasonCodeId?: string) => `${BASE}/money/demands/${id}/cancel${qs({ reasonCodeId })}`,
    previewAllocation: `${BASE}/money/receipts/preview`,
    createReceipt: `${BASE}/money/receipts`,
    searchReceipts: `${BASE}/money/receipts/search`,
    getReceipt: (id: string) => `${BASE}/money/receipts/${id}`,
    reverseReceipt: (id: string, reasonCodeId?: string, note?: string) => `${BASE}/money/receipts/${id}/reverse${qs({ reasonCodeId, note })}`,
    reallocate: (id: string, reason?: string) => `${BASE}/money/receipts/${id}/reallocate${qs({ reason })}`,
    getCheques: (query?: M.ListQueryDto, state?: E.ChequeState) => `${BASE}/money/cheques${qs({ query, state })}`,
    changeChequeState: `${BASE}/money/cheques/state`,
    getMaturity: (from?: string, to?: string) => `${BASE}/money/cheques/maturity${qs({ from, to })}`,
    getLedger: (bookingId?: string, partyId?: string, query?: M.ListQueryDto) => `${BASE}/money/ledger${qs({ bookingId, partyId, query })}`,
    getStatement: (bookingId: string, from?: string, to?: string) => `${BASE}/money/statements/${bookingId}${qs({ from, to })}`,
    getWorklist: `${BASE}/money/worklist`,
    recordPromise: `${BASE}/money/promises`,
    getPromises: (dueOn?: string, state?: E.PromiseState) => `${BASE}/money/promises${qs({ dueOn, state })}`,
    evaluatePromises: `${BASE}/money/promises/evaluate`,
    getDunningPolicies: (appliesTo?: string) => `${BASE}/money/dunning-policies${qs({ appliesTo })}`,
    saveDunningPolicy: `${BASE}/money/dunning-policies`,
    getDunningCases: (query?: M.ListQueryDto, openOnly?: boolean) => `${BASE}/money/dunning${qs({ query, openOnly })}`,
    getDunningCase: (id: string) => `${BASE}/money/dunning/${id}`,
    suspendDunning: (id: string, until?: string, reason?: string) => `${BASE}/money/dunning/${id}/suspend${qs({ until, reason })}`,
    runDunning: (asOf?: string) => `${BASE}/money/dunning/run${qs({ asOf })}`,
    issueNotice: (bookingId?: string, tenancyId?: string, noticeType?: string, complyBy?: string, templateId?: string) => `${BASE}/money/notices${qs({ bookingId, tenancyId, noticeType, complyBy, templateId })}`,
    recordService: (id: string, method?: string, reference?: string, evidenceUrl?: string, servedOn?: string) => `${BASE}/money/notices/${id}/service${qs({ method, reference, evidenceUrl, servedOn })}`,
    getNotices: (query?: M.ListQueryDto) => `${BASE}/money/notices${qs({ query })}`,
    requestWriteOff: `${BASE}/money/write-offs`,
    decideWriteOff: (id: string, outcome?: E.ApprovalOutcome, comment?: string) => `${BASE}/money/write-offs/${id}/decide${qs({ outcome, comment })}`,
  },

  project: {
    getAll: (query?: M.ListQueryDto) => `${BASE}/projects${qs({ query })}`,
    lookup: `${BASE}/projects/lookup`,
    get: (id: string) => `${BASE}/projects/${id}`,
    save: `${BASE}/projects`,
    getStructure: (id: string) => `${BASE}/projects/${id}/structure`,
    saveNode: `${BASE}/projects/nodes`,
    deleteNode: (nodeId: string) => `${BASE}/projects/nodes/${nodeId}`,
    generateUnits: `${BASE}/projects/generate-units`,
    getMilestones: (id: string) => `${BASE}/projects/${id}/milestones`,
    saveMilestone: `${BASE}/projects/milestones`,
    certifyMilestone: `${BASE}/projects/milestones/certify`,
    getBudget: (id: string) => `${BASE}/projects/${id}/budget`,
    saveBudgetLine: (id: string) => `${BASE}/projects/${id}/budget`,
    getCashFlow: (id: string, months?: number) => `${BASE}/projects/${id}/cash-flow${qs({ months })}`,
    getSitePlans: (id: string) => `${BASE}/projects/${id}/site-plans`,
    saveSitePlan: (id: string) => `${BASE}/projects/${id}/site-plans`,
    saveShapes: (sitePlanId: string) => `${BASE}/projects/site-plans/${sitePlanId}/shapes`,
    getPlotFiles: (id: string, query?: M.ListQueryDto) => `${BASE}/projects/${id}/plot-files${qs({ query })}`,
    issuePlotFiles: (id: string, categoryCode?: string, count?: number, price?: number, areaSqFt?: number) => `${BASE}/projects/${id}/plot-files${qs({ categoryCode, count, price, areaSqFt })}`,
  },

  property: {
    search: `${BASE}/properties/search`,
    get: (id: string) => `${BASE}/properties/${id}`,
    save: `${BASE}/properties`,
    delete: (id: string) => `${BASE}/properties/${id}`,
    checkDuplicates: `${BASE}/properties/check-duplicates`,
    changeStatus: (id: string, status?: E.PropertyStatus, reasonCodeId?: string, note?: string) => `${BASE}/properties/${id}/status${qs({ status, reasonCodeId, note })}`,
    saveMedia: (id: string) => `${BASE}/properties/${id}/media`,
    deleteMedia: (mediaId: string) => `${BASE}/properties/media/${mediaId}`,
    getDocuments: (id: string) => `${BASE}/properties/${id}/documents`,
    saveDocument: (id: string) => `${BASE}/properties/${id}/documents`,
    getOwnership: (id: string, includeHistory?: boolean) => `${BASE}/properties/${id}/ownership${qs({ includeHistory })}`,
    setOwner: (id: string) => `${BASE}/properties/${id}/ownership`,
    getValuations: (id: string) => `${BASE}/properties/${id}/valuations`,
    saveValuation: `${BASE}/properties/valuations`,
    getPriceOpinion: (id: string, kind?: E.ListingKind) => `${BASE}/properties/${id}/price-opinion${qs({ kind })}`,
    findComparables: (id: string, take?: number) => `${BASE}/properties/${id}/comparables${qs({ take })}`,
    getParcels: (query?: M.ListQueryDto) => `${BASE}/properties/parcels${qs({ query })}`,
    getParcel: (id: string) => `${BASE}/properties/parcels/${id}`,
    saveParcel: `${BASE}/properties/parcels`,
    saveTitleEntry: (id: string) => `${BASE}/properties/parcels/${id}/title-chain`,
    saveEncumbrance: (parcelId?: string, propertyId?: string) => `${BASE}/properties/encumbrances${qs({ parcelId, propertyId })}`,
    saveVerification: (id: string) => `${BASE}/properties/parcels/${id}/verifications`,
    getAcquisitions: (query?: M.ListQueryDto) => `${BASE}/properties/acquisitions${qs({ query })}`,
    saveAcquisition: `${BASE}/properties/acquisitions`,
    saveAcquisitionCost: (id: string) => `${BASE}/properties/acquisitions/${id}/costs`,
  },

  report: {
    getDashboard: (officeId?: string, projectId?: string) => `${BASE}/reports/dashboard${qs({ officeId, projectId })}`,
    getAttention: (officeId?: string, projectId?: string) => `${BASE}/reports/attention${qs({ officeId, projectId })}`,
    getPortfolio: (query?: M.ListQueryDto) => `${BASE}/reports/portfolio${qs({ query })}`,
    getCatalogue: `${BASE}/reports/catalogue`,
    run: `${BASE}/reports/run`,
  },

  society: {
    getAll: (query?: M.ListQueryDto) => `${BASE}/societies${qs({ query })}`,
    get: (id: string) => `${BASE}/societies/${id}`,
    save: `${BASE}/societies`,
    getDashboard: (id: string) => `${BASE}/societies/${id}/dashboard`,
    handOver: (id: string, handoverDate?: string, corpusTransferred?: number) => `${BASE}/societies/${id}/handover${qs({ handoverDate, corpusTransferred })}`,
    getCommittee: (id: string) => `${BASE}/societies/${id}/committee`,
    saveCommitteeMember: (id: string) => `${BASE}/societies/${id}/committee`,
    getResidents: (id: string, query?: M.ListQueryDto, kind?: E.ResidentKind, defaultersOnly?: boolean) => `${BASE}/societies/${id}/residents${qs({ query, kind, defaultersOnly })}`,
    getResident: (id: string) => `${BASE}/societies/residents/${id}`,
    saveResident: `${BASE}/societies/residents`,
    moveOut: (id: string, movedOutOn?: string) => `${BASE}/societies/residents/${id}/move-out${qs({ movedOutOn })}`,
    saveVehicle: (id: string) => `${BASE}/societies/residents/${id}/vehicles`,
    getStaff: (id: string, query?: M.ListQueryDto) => `${BASE}/societies/${id}/staff${qs({ query })}`,
    saveStaff: `${BASE}/societies/staff`,
    getChargeSchemes: (id: string) => `${BASE}/societies/${id}/charge-schemes`,
    saveChargeScheme: `${BASE}/societies/charge-schemes`,
    runBilling: `${BASE}/societies/billing/run`,
    getBills: (id: string, query?: M.ListQueryDto, status?: E.InstalmentStatus) => `${BASE}/societies/${id}/bills${qs({ query, status })}`,
    getBill: (id: string) => `${BASE}/societies/bills/${id}`,
    getCharges: (id: string, unitId?: string) => `${BASE}/societies/${id}/charges${qs({ unitId })}`,
    saveCharge: `${BASE}/societies/charges`,
    imposePenalty: `${BASE}/societies/penalties`,
    waivePenalty: (id: string, reason?: string) => `${BASE}/societies/penalties/${id}/waive${qs({ reason })}`,
    getPenalties: (id: string, query?: M.ListQueryDto) => `${BASE}/societies/${id}/penalties${qs({ query })}`,
    createVisitorPass: `${BASE}/societies/visitor-passes`,
    getVisitorPasses: (id: string, query?: M.ListQueryDto, unitId?: string) => `${BASE}/societies/${id}/visitor-passes${qs({ query, unitId })}`,
    recordEntry: `${BASE}/societies/gate/entries`,
    approveEntry: `${BASE}/societies/gate/approve`,
    checkOut: (id: string) => `${BASE}/societies/gate/entries/${id}/check-out`,
    getGateLog: (id: string, query?: M.ListQueryDto, status?: E.GateEntryStatus) => `${BASE}/societies/${id}/gate/log${qs({ query, status })}`,
    getInsideNow: (id: string) => `${BASE}/societies/${id}/gate/inside-now`,
    syncGate: `${BASE}/societies/gate/sync`,
    createGatePass: `${BASE}/societies/gate/passes`,
    createMoveRequest: `${BASE}/societies/moves`,
    decideMoveRequest: (id: string, status?: string) => `${BASE}/societies/moves/${id}/decide${qs({ status })}`,
    getAmenities: (id: string) => `${BASE}/societies/${id}/amenities`,
    saveAmenity: `${BASE}/societies/amenities`,
    getAvailability: (id: string, date?: string) => `${BASE}/societies/amenities/${id}/availability${qs({ date })}`,
    bookAmenity: `${BASE}/societies/amenities/bookings`,
    decideBooking: (id: string, approved?: boolean, reason?: string) => `${BASE}/societies/amenities/bookings/${id}/decide${qs({ approved, reason })}`,
    cancelBooking: (id: string, reason?: string) => `${BASE}/societies/amenities/bookings/${id}/cancel${qs({ reason })}`,
    getBookings: (id: string, query?: M.ListQueryDto, status?: E.AmenityBookingStatus) => `${BASE}/societies/${id}/amenities/bookings${qs({ query, status })}`,
    createComplaint: `${BASE}/societies/complaints`,
    getComplaint: (id: string) => `${BASE}/societies/complaints/${id}`,
    searchComplaints: `${BASE}/societies/complaints/search`,
    updateComplaint: (id: string, status?: E.TicketStatus, note?: string, visibleToResident?: boolean) => `${BASE}/societies/complaints/${id}/update${qs({ status, note, visibleToResident })}`,
    assignComplaint: (id: string, assignToUserId?: string, contractorId?: string) => `${BASE}/societies/complaints/${id}/assign${qs({ assignToUserId, contractorId })}`,
    rateComplaint: (id: string, rating?: number, note?: string) => `${BASE}/societies/complaints/${id}/rate${qs({ rating, note })}`,
    escalateBreached: `${BASE}/societies/complaints/escalate`,
    getNotices: (id: string, query?: M.ListQueryDto) => `${BASE}/societies/${id}/notices${qs({ query })}`,
    saveNotice: `${BASE}/societies/notices`,
    getPolls: (id: string, openOnly?: boolean) => `${BASE}/societies/${id}/polls${qs({ openOnly })}`,
    savePoll: `${BASE}/societies/polls`,
    vote: (id: string, unitId?: string, choice?: string, comment?: string) => `${BASE}/societies/polls/${id}/vote${qs({ unitId, choice, comment })}`,
    getBuildingApplications: (id: string, query?: M.ListQueryDto, status?: E.BuildingApplicationStatus) => `${BASE}/societies/${id}/building-applications${qs({ query, status })}`,
    getBuildingApplication: (id: string) => `${BASE}/societies/building-applications/${id}`,
    saveBuildingApplication: `${BASE}/societies/building-applications`,
    decideBuildingApplication: (id: string, status?: E.BuildingApplicationStatus, conditions?: string, rejectionReason?: string) => `${BASE}/societies/building-applications/${id}/decide${qs({ status, conditions, rejectionReason })}`,
    recordBuildingInspection: `${BASE}/societies/building-inspections`,
    issueViolation: `${BASE}/societies/violations`,
    closeViolation: (id: string, compliedOn?: string) => `${BASE}/societies/violations/${id}/close${qs({ compliedOn })}`,
    getViolations: (id: string, query?: M.ListQueryDto, openOnly?: boolean) => `${BASE}/societies/${id}/violations${qs({ query, openOnly })}`,
  },

} as const;
