import { environment } from '@env';
const BASE_URL = environment.apiBaseUrl;

export const SALES_API = {
  company: {
    getById: (id: string) => `${BASE_URL}/api/Company/${id}`,
  },
  geo: {
    currencies: `${BASE_URL}/api/core/geo/currencies`,
  },
  coupon: {
    getAll: `${BASE_URL}/api/sales/Coupon`,
    getById: (id: string) => `${BASE_URL}/api/sales/Coupon/${id}`,
    create: `${BASE_URL}/api/sales/Coupon`,
    delete: (id: string) => `${BASE_URL}/api/sales/Coupon/${id}`,
    active: `${BASE_URL}/api/sales/Coupon/active`,
    validate: (code: string, customerId?: string) =>
      customerId
        ? `${BASE_URL}/api/sales/Coupon/validate/${code}?customerId=${customerId}`
        : `${BASE_URL}/api/sales/Coupon/validate/${code}`,
  },
  delivery: {
    getAll: `${BASE_URL}/api/sales/Delivery`,
    getById: (id: string) => `${BASE_URL}/api/sales/Delivery/${id}`,
    create: `${BASE_URL}/api/sales/Delivery`,
    delete: (id: string) => `${BASE_URL}/api/sales/Delivery/${id}`,
    byNumber: (n: string) => `${BASE_URL}/api/sales/Delivery/by-number/${n}`,
    byOrder: (id: string) => `${BASE_URL}/api/sales/Delivery/by-order/${id}`,
    byStatus: (s: string) => `${BASE_URL}/api/sales/Delivery/by-status/${s}`,
    ship: (id: string) => `${BASE_URL}/api/sales/Delivery/${id}/ship`,
    deliver: (id: string) => `${BASE_URL}/api/sales/Delivery/${id}/deliver`,
  },
  posCashier: {
    byStore: (storeId: string) => `${BASE_URL}/api/sales/PosCashier/store/${storeId}`,
    getById: (id: string) => `${BASE_URL}/api/sales/PosCashier/${id}`,
    create: `${BASE_URL}/api/sales/PosCashier`,
    update: (id: string) => `${BASE_URL}/api/sales/PosCashier/${id}`,
    delete: (id: string) => `${BASE_URL}/api/sales/PosCashier/${id}`,
    setPin: (id: string) => `${BASE_URL}/api/sales/PosCashier/${id}/set-pin`,
    changePin: (id: string) => `${BASE_URL}/api/sales/PosCashier/${id}/change-pin`,
    pinLogin: `${BASE_URL}/api/sales/PosCashier/pin-login`,
    checkIn: `${BASE_URL}/api/sales/PosCashier/check-in`,
    checkOut: (sessionId: string) => `${BASE_URL}/api/sales/PosCashier/check-out/${sessionId}`,
    openSession: `${BASE_URL}/api/sales/PosCashier/open-session`,
    sessionsByTerminal: (terminalId: string) => `${BASE_URL}/api/sales/PosCashier/sessions/by-terminal/${terminalId}`,
    sessionsByDate: `${BASE_URL}/api/sales/PosCashier/sessions/by-date`,
    cashIn: (sessionId: string) => `${BASE_URL}/api/sales/PosCashier/sessions/${sessionId}/cash-in`,
    cashOut: (sessionId: string) => `${BASE_URL}/api/sales/PosCashier/sessions/${sessionId}/cash-out`,
    cashMovements: (sessionId: string) => `${BASE_URL}/api/sales/PosCashier/sessions/${sessionId}/cash-movements`,
  },
  posStore: {
    getAll: `${BASE_URL}/api/sales/PosStore`,
    getById: (id: string) => `${BASE_URL}/api/sales/PosStore/${id}`,
    create: `${BASE_URL}/api/sales/PosStore`,
    update: (id: string) => `${BASE_URL}/api/sales/PosStore/${id}`,
    delete: (id: string) => `${BASE_URL}/api/sales/PosStore/${id}`,
    active: `${BASE_URL}/api/sales/PosStore/active`,
    onlineEnabled: `${BASE_URL}/api/sales/PosStore/online-enabled`,
    menu: (id: string) => `${BASE_URL}/api/sales/PosStore/${id}/menu`,
    nearby: (lat: number, lng: number, radiusKm = 5) =>
      `${BASE_URL}/api/sales/PosStore/nearby?lat=${lat}&lng=${lng}&radiusKm=${radiusKm}`,
    setOnlineStatus: (id: string) => `${BASE_URL}/api/sales/PosStore/${id}/online-status`,
    vendorProfile: (storeId: string) => `${BASE_URL}/api/sales/PosStore/${storeId}/vendor-profile`,
    upsertVendorProfile: (storeId: string) => `${BASE_URL}/api/sales/PosStore/${storeId}/vendor-profile`,
    submitVendorApplication: (storeId: string) => `${BASE_URL}/api/sales/PosStore/${storeId}/vendor-profile/submit`,
    pendingVendorApplications: `${BASE_URL}/api/sales/vendor-applications/pending`,
    reviewVendorApplication: (storeId: string) => `${BASE_URL}/api/sales/PosStore/${storeId}/vendor-profile/review`,
    detectCountry: `${BASE_URL}/api/sales/PosStore/detect-country`,
  },
  priceList: {
    getAll: `${BASE_URL}/api/sales/PriceList`,
    getById: (id: string) => `${BASE_URL}/api/sales/PriceList/${id}`,
    create: `${BASE_URL}/api/sales/PriceList`,
    update: (id: string) => `${BASE_URL}/api/sales/PriceList/${id}`,
    delete: (id: string) => `${BASE_URL}/api/sales/PriceList/${id}`,
    byCode: (code: string) => `${BASE_URL}/api/sales/PriceList/by-code/${code}`,
    active: `${BASE_URL}/api/sales/PriceList/active`,
    // Lines — what a price list actually prices.
    items: (id: string) => `${BASE_URL}/api/sales/PriceList/${id}/items`,
    updateItem: (itemId: string) => `${BASE_URL}/api/sales/PriceList/items/${itemId}`,
    deleteItem: (itemId: string) => `${BASE_URL}/api/sales/PriceList/items/${itemId}`,
  },
  quotation: {
    getAll: `${BASE_URL}/api/sales/Quotation`,
    getById: (id: string) => `${BASE_URL}/api/sales/Quotation/${id}`,
    create: `${BASE_URL}/api/sales/Quotation`,
    delete: (id: string) => `${BASE_URL}/api/sales/Quotation/${id}`,
    byNumber: (n: string) => `${BASE_URL}/api/sales/Quotation/by-number/${n}`,
    byCustomer: (id: string) => `${BASE_URL}/api/sales/Quotation/by-customer/${id}`,
    byStatus: (s: string) => `${BASE_URL}/api/sales/Quotation/by-status/${s}`,
    send: (id: string) => `${BASE_URL}/api/sales/Quotation/${id}/send`,
    accept: (id: string) => `${BASE_URL}/api/sales/Quotation/${id}/accept`,
  },
  rider: {
    getAll: `${BASE_URL}/api/sales/Rider`,
    getById: (id: string) => `${BASE_URL}/api/sales/Rider/${id}`,
    create: `${BASE_URL}/api/sales/Rider`,
    update: (id: string) => `${BASE_URL}/api/sales/Rider/${id}`,
    delete: (id: string) => `${BASE_URL}/api/sales/Rider/${id}`,
    byStore: (storeId: string) => `${BASE_URL}/api/sales/Rider/by-store/${storeId}`,
    available: `${BASE_URL}/api/sales/Rider/available`,
    assign: `${BASE_URL}/api/sales/Rider/assign`,
    activeAssignment: (orderId: string) => `${BASE_URL}/api/sales/Rider/assignment/active/${orderId}`,
  },
  salesInvoice: {
    getAll: `${BASE_URL}/api/sales/SalesInvoice`,
    getById: (id: string) => `${BASE_URL}/api/sales/SalesInvoice/${id}`,
    create: `${BASE_URL}/api/sales/SalesInvoice`,
    byNumber: (n: string) => `${BASE_URL}/api/sales/SalesInvoice/by-number/${n}`,
    byCustomer: (id: string) => `${BASE_URL}/api/sales/SalesInvoice/by-customer/${id}`,
    byOrder: (id: string) => `${BASE_URL}/api/sales/SalesInvoice/by-order/${id}`,
    overdue: `${BASE_URL}/api/sales/SalesInvoice/overdue`,
    confirm: (id: string) => `${BASE_URL}/api/sales/SalesInvoice/${id}/confirm`,
    resetToDraft: (id: string) => `${BASE_URL}/api/sales/SalesInvoice/${id}/reset-to-draft`,
    registerPayment: (id: string) => `${BASE_URL}/api/sales/SalesInvoice/${id}/register-payment`,
    send: (id: string) => `${BASE_URL}/api/sales/SalesInvoice/${id}/send`,
    creditNote: (id: string) => `${BASE_URL}/api/sales/SalesInvoice/${id}/credit-note`,
    cancel: (id: string) => `${BASE_URL}/api/sales/SalesInvoice/${id}/cancel`,
    document: (id: string) => `${BASE_URL}/api/sales/SalesInvoice/${id}/document`,
  },
  salesOrder: {
    getAll: `${BASE_URL}/api/sales/SalesOrder`,
    getById: (id: string) => `${BASE_URL}/api/sales/SalesOrder/${id}`,
    getFull: (id: string) => `${BASE_URL}/api/sales/SalesOrder/${id}/full`,
    create: `${BASE_URL}/api/sales/SalesOrder`,
    delete: (id: string) => `${BASE_URL}/api/sales/SalesOrder/${id}`,
    byNumber: (n: string) => `${BASE_URL}/api/sales/SalesOrder/by-number/${n}`,
    byStatus: (s: string) => `${BASE_URL}/api/sales/SalesOrder/by-status/${s}`,
    byChannel: (c: string) => `${BASE_URL}/api/sales/SalesOrder/by-channel/${c}`,
    activeDrafts: (contactId: string) => `${BASE_URL}/api/sales/SalesOrder/active-drafts/${contactId}`,
    byCustomer: (id: string) => `${BASE_URL}/api/sales/SalesOrder/by-customer/${id}`,
    storeQueue: (storeId: string) => `${BASE_URL}/api/sales/SalesOrder/store-queue/${storeId}`,
    place: (id: string) => `${BASE_URL}/api/sales/SalesOrder/${id}/place`,
    updateStatus: (id: string) => `${BASE_URL}/api/sales/SalesOrder/${id}/status`,
    toInvoice: `${BASE_URL}/api/sales/SalesOrder/to-invoice`,
    createInvoice: (id: string) => `${BASE_URL}/api/sales/SalesOrder/${id}/create-invoice`,
    lock: (id: string) => `${BASE_URL}/api/sales/SalesOrder/${id}/lock`,
    unlock: (id: string) => `${BASE_URL}/api/sales/SalesOrder/${id}/unlock`,
    phoneOrder: `${BASE_URL}/api/sales/SalesOrder/phone-order`,
    syncOffline: `${BASE_URL}/api/sales/SalesOrder/sync-offline`,
  },
  promotion: {
    getAll: `${BASE_URL}/api/sales/Promotion`,
    getById: (id: string) => `${BASE_URL}/api/sales/Promotion/${id}`,
    create: `${BASE_URL}/api/sales/Promotion`,
    update: (id: string) => `${BASE_URL}/api/sales/Promotion/${id}`,
    delete: (id: string) => `${BASE_URL}/api/sales/Promotion/${id}`,
    active: (at?: string) => at ? `${BASE_URL}/api/sales/Promotion/active?at=${encodeURIComponent(at)}` : `${BASE_URL}/api/sales/Promotion/active`,
    activate: (id: string) => `${BASE_URL}/api/sales/Promotion/${id}/activate`,
    pause: (id: string) => `${BASE_URL}/api/sales/Promotion/${id}/pause`,
    cancel: (id: string) => `${BASE_URL}/api/sales/Promotion/${id}/cancel`,
    addItem: (id: string) => `${BASE_URL}/api/sales/Promotion/${id}/items`,
    deleteItem: (id: string, itemId: string) => `${BASE_URL}/api/sales/Promotion/${id}/items/${itemId}`,
  },
  storeOffer: {
    byStore: (storeId: string) => `${BASE_URL}/api/sales/StoreOffer/store/${storeId}`,
    byStoreAll: (storeId: string) => `${BASE_URL}/api/sales/StoreOffer/store/${storeId}/all`,
    getAll: `${BASE_URL}/api/sales/StoreOffer`,
    getById: (id: string) => `${BASE_URL}/api/sales/StoreOffer/${id}`,
    create: `${BASE_URL}/api/sales/StoreOffer`,
    update: (id: string) => `${BASE_URL}/api/sales/StoreOffer/${id}`,
    delete: (id: string) => `${BASE_URL}/api/sales/StoreOffer/${id}`,
    toggle: (id: string) => `${BASE_URL}/api/sales/StoreOffer/${id}/toggle`,
  },
  posDashboard: {
    branchStatus: (branchId: string) => `${BASE_URL}/api/sales/pos/dashboard/branch/${branchId}`,
    bulkBranchStatus: `${BASE_URL}/api/sales/pos/dashboard/branches`,
    terminalStatuses: `${BASE_URL}/api/sales/pos/dashboard/terminals`,
  },
  posReport: {
    xRead: (sessionId: string) => `${BASE_URL}/api/sales/PosReport/session/${sessionId}/x`,
    zRead: (sessionId: string) => `${BASE_URL}/api/sales/PosReport/session/${sessionId}/z`,
    salesSummary: `${BASE_URL}/api/sales/PosReport/sales-summary`,
    byProduct: `${BASE_URL}/api/sales/PosReport/by-product`,
    byCashier: `${BASE_URL}/api/sales/PosReport/by-cashier`,
    byHour: `${BASE_URL}/api/sales/PosReport/by-hour`,
    tenderMix: `${BASE_URL}/api/sales/PosReport/tender-mix`,
  },
  pricing: {
    quote: `${BASE_URL}/api/sales/Pricing/quote`,
  },
  posTransaction: {
    checkout: `${BASE_URL}/api/sales/PosTransaction/checkout`,
    offlineSync: `${BASE_URL}/api/sales/PosTransaction/offline-sync`,
    getById: (id: string) => `${BASE_URL}/api/sales/PosTransaction/${id}`,
    byNumber: (n: string) => `${BASE_URL}/api/sales/PosTransaction/by-number/${n}`,
    bySession: (sessionId: string) => `${BASE_URL}/api/sales/PosTransaction/by-session/${sessionId}`,
    byDate: (from: string, to?: string) => {
      const params = new URLSearchParams({ from });
      if (to) params.append('to', to);
      return `${BASE_URL}/api/sales/PosTransaction/by-date?${params.toString()}`;
    },
    receipt: (id: string, paperSize?: string) =>
      paperSize
        ? `${BASE_URL}/api/sales/PosTransaction/${id}/receipt?paperSize=${encodeURIComponent(paperSize)}`
        : `${BASE_URL}/api/sales/PosTransaction/${id}/receipt`,
    receiptHtml: (id: string) => `${BASE_URL}/api/sales/PosTransaction/${id}/receipt/html`,
    receiptPdf: (id: string) => `${BASE_URL}/api/sales/PosTransaction/${id}/receipt/pdf`,
  },
  salesLookup: {
    orderStatuses: `${BASE_URL}/api/sales/SalesLookup/order-statuses`,
    salesChannels: `${BASE_URL}/api/sales/SalesLookup/sales-channels`,
    fulfillmentTypes: `${BASE_URL}/api/sales/SalesLookup/fulfillment-types`,
    quotationStatuses: `${BASE_URL}/api/sales/SalesLookup/quotation-statuses`,
    deliveryStatuses: `${BASE_URL}/api/sales/SalesLookup/delivery-statuses`,
    invoiceStatuses: `${BASE_URL}/api/sales/SalesLookup/invoice-statuses`,
    incoterms: `${BASE_URL}/api/sales/SalesLookup/incoterms`,
    returnStatuses: `${BASE_URL}/api/sales/SalesLookup/return-statuses`,
    discountTypes: `${BASE_URL}/api/sales/SalesLookup/discount-types`,
    couponStatuses: `${BASE_URL}/api/sales/SalesLookup/coupon-statuses`,
    priceListTypes: `${BASE_URL}/api/sales/SalesLookup/price-list-types`,
    paymentTerms: `${BASE_URL}/api/sales/SalesLookup/payment-terms`,
    taxCategories: `${BASE_URL}/api/sales/SalesLookup/tax-categories`,
    posStoreTypes: `${BASE_URL}/api/sales/SalesLookup/pos-store-types`,
    storeOnlineStatuses: `${BASE_URL}/api/sales/SalesLookup/store-online-statuses`,
    posSessionStatuses: `${BASE_URL}/api/sales/SalesLookup/pos-session-statuses`,
    posTransactionStatuses: `${BASE_URL}/api/sales/SalesLookup/pos-transaction-statuses`,
    posTransactionTypes: `${BASE_URL}/api/sales/SalesLookup/pos-transaction-types`,
    posTenderTypes: `${BASE_URL}/api/sales/SalesLookup/pos-tender-types`,
    posCashMovementTypes: `${BASE_URL}/api/sales/SalesLookup/pos-cash-movement-types`,
    riderStatuses: `${BASE_URL}/api/sales/SalesLookup/rider-statuses`,
    riderAssignmentStatuses: `${BASE_URL}/api/sales/SalesLookup/rider-assignment-statuses`,
    vehicleTypes: `${BASE_URL}/api/sales/SalesLookup/vehicle-types`,
    loyaltyTiers: `${BASE_URL}/api/sales/SalesLookup/loyalty-tiers`,
    loyaltyTransactionTypes: `${BASE_URL}/api/sales/SalesLookup/loyalty-transaction-types`,
    giftCardStatuses: `${BASE_URL}/api/sales/SalesLookup/gift-card-statuses`,
    approvalDecisions: `${BASE_URL}/api/sales/SalesLookup/approval-decisions`,
    approvalConditionFields: `${BASE_URL}/api/sales/SalesLookup/approval-condition-fields`,
    approvalConditionOperators: `${BASE_URL}/api/sales/SalesLookup/approval-condition-operators`,
    commissionBases: `${BASE_URL}/api/sales/SalesLookup/commission-bases`,
    commissionStatuses: `${BASE_URL}/api/sales/SalesLookup/commission-statuses`,
    targetPeriods: `${BASE_URL}/api/sales/SalesLookup/target-periods`,
    salesAgreementStatuses: `${BASE_URL}/api/sales/SalesLookup/sales-agreement-statuses`,
    promotionStatuses: `${BASE_URL}/api/sales/SalesLookup/promotion-statuses`,
    promotionDiscountTypes: `${BASE_URL}/api/sales/SalesLookup/promotion-discount-types`,
    promotionConditionTypes: `${BASE_URL}/api/sales/SalesLookup/promotion-condition-types`,
    promotionTargetTypes: `${BASE_URL}/api/sales/SalesLookup/promotion-target-types`,
    promotionPriceTargets: `${BASE_URL}/api/sales/SalesLookup/promotion-price-targets`,
    scheduledDays: `${BASE_URL}/api/sales/SalesLookup/scheduled-days`,
    storeOfferTypes: `${BASE_URL}/api/sales/SalesLookup/store-offer-types`,
    posStoreFormats: `${BASE_URL}/api/sales/SalesLookup/pos-store-formats`,
    notificationChannels: `${BASE_URL}/api/sales/SalesLookup/notification-channels`,
    notificationTypes: `${BASE_URL}/api/sales/SalesLookup/notification-types`,
  },
  salesPayment: {
    getAll: `${BASE_URL}/api/sales/SalesPayment`,
    getById: (id: string) => `${BASE_URL}/api/sales/SalesPayment/${id}`,
    create: `${BASE_URL}/api/sales/SalesPayment`,
    byNumber: (n: string) => `${BASE_URL}/api/sales/SalesPayment/by-number/${n}`,
    byCustomer: (id: string) => `${BASE_URL}/api/sales/SalesPayment/by-customer/${id}`,
    byOrder: (id: string) => `${BASE_URL}/api/sales/SalesPayment/by-order/${id}`,
    byInvoice: (id: string) => `${BASE_URL}/api/sales/SalesPayment/by-invoice/${id}`,
  },
  posTerminal: {
    byBranch: (branchId: string) => `${BASE_URL}/api/sales/PosTerminal/branch/${branchId}`,
    activeByBranch: (branchId: string) => `${BASE_URL}/api/sales/PosTerminal/branch/${branchId}/active`,
    getById: (id: string) => `${BASE_URL}/api/sales/PosTerminal/${id}`,
    create: `${BASE_URL}/api/sales/PosTerminal`,
    update: (id: string) => `${BASE_URL}/api/sales/PosTerminal/${id}`,
    delete: (id: string) => `${BASE_URL}/api/sales/PosTerminal/${id}`,
    heartbeat: (id: string) => `${BASE_URL}/api/sales/PosTerminal/${id}/heartbeat`,
    goOffline: (id: string) => `${BASE_URL}/api/sales/PosTerminal/${id}/go-offline`,
  },
  posReceiptTemplate: {
    getAll: `${BASE_URL}/api/sales/PosReceiptTemplate`,
    getById: (id: string) => `${BASE_URL}/api/sales/PosReceiptTemplate/${id}`,
    create: `${BASE_URL}/api/sales/PosReceiptTemplate`,
    update: (id: string) => `${BASE_URL}/api/sales/PosReceiptTemplate/${id}`,
    delete: (id: string) => `${BASE_URL}/api/sales/PosReceiptTemplate/${id}`,
    getDefault: `${BASE_URL}/api/sales/PosReceiptTemplate/default`,
    setDefault: (id: string) => `${BASE_URL}/api/sales/PosReceiptTemplate/${id}/set-default`,
    uploadLogo: (id: string) => `${BASE_URL}/api/sales/PosReceiptTemplate/${id}/upload-logo`,
    deleteLogo: (id: string) => `${BASE_URL}/api/sales/PosReceiptTemplate/${id}/logo`,
  },
  posSettings: {
    get: `${BASE_URL}/api/sales/PosSettings`,
    update: `${BASE_URL}/api/sales/PosSettings`,
    reset: `${BASE_URL}/api/sales/PosSettings/reset`,
    cashDrawers: {
      byStore: (storeId: string) => `${BASE_URL}/api/sales/PosSettings/cash-drawers/store/${storeId}`,
      activeByStore: (storeId: string) => `${BASE_URL}/api/sales/PosSettings/cash-drawers/store/${storeId}/active`,
      getById: (id: string) => `${BASE_URL}/api/sales/PosSettings/cash-drawers/${id}`,
      create: `${BASE_URL}/api/sales/PosSettings/cash-drawers`,
      update: (id: string) => `${BASE_URL}/api/sales/PosSettings/cash-drawers/${id}`,
      delete: (id: string) => `${BASE_URL}/api/sales/PosSettings/cash-drawers/${id}`,
    },
  },
  currency: {
    getAll: `${BASE_URL}/api/sales/Currency`,
    getBase: `${BASE_URL}/api/sales/Currency/base`,
    getByCode: (code: string) => `${BASE_URL}/api/sales/Currency/${code}`,
    create: `${BASE_URL}/api/sales/Currency`,
    update: (id: string) => `${BASE_URL}/api/sales/Currency/${id}`,
    getRates: (id: string) => `${BASE_URL}/api/sales/Currency/${id}/rates`,
    addRate: (id: string) => `${BASE_URL}/api/sales/Currency/${id}/rates`,
    updateRate: (rateId: string) => `${BASE_URL}/api/sales/Currency/rates/${rateId}`,
    deleteRate: (rateId: string) => `${BASE_URL}/api/sales/Currency/rates/${rateId}`,
    latestRates: (asOfDate?: string) =>
      asOfDate
        ? `${BASE_URL}/api/sales/Currency/rates/latest?asOfDate=${asOfDate}`
        : `${BASE_URL}/api/sales/Currency/rates/latest`,
    rateHistory: (code: string, fromDate?: string, toDate?: string) => {
      const params = new URLSearchParams();
      if (fromDate) params.append('fromDate', fromDate);
      if (toDate) params.append('toDate', toDate);
      const qs = params.toString();
      return `${BASE_URL}/api/sales/Currency/${code}/rates/history${qs ? '?' + qs : ''}`;
    },
    convert: `${BASE_URL}/api/sales/Currency/convert`,
    bulkConvert: `${BASE_URL}/api/sales/Currency/bulk-convert`,
    rateLookup: (from: string, to: string, rateType?: number, rateName?: string, asOfDate?: string) => {
      const params = new URLSearchParams({ from, to });
      if (rateType !== undefined) params.append('rateType', String(rateType));
      if (rateName) params.append('rateName', rateName);
      if (asOfDate) params.append('asOfDate', asOfDate);
      return `${BASE_URL}/api/sales/Currency/rate-lookup?${params.toString()}`;
    },
  },
  documentSequence: {
    getAll: `${BASE_URL}/api/sales/DocumentSequence`,
    getByDocumentType: (documentType: string) => `${BASE_URL}/api/sales/DocumentSequence/${documentType}`,
    create: `${BASE_URL}/api/sales/DocumentSequence`,
    update: (id: string) => `${BASE_URL}/api/sales/DocumentSequence/${id}`,
    reset: (id: string) => `${BASE_URL}/api/sales/DocumentSequence/${id}/reset`,
    preview: `${BASE_URL}/api/sales/DocumentSequence/preview`,
  },
  salesTeam: {
    getAll: `${BASE_URL}/api/sales/SalesTeam`,
    getActive: `${BASE_URL}/api/sales/SalesTeam/active`,
    getById: (id: string) => `${BASE_URL}/api/sales/SalesTeam/${id}`,
    create: `${BASE_URL}/api/sales/SalesTeam`,
    update: (id: string) => `${BASE_URL}/api/sales/SalesTeam/${id}`,
    delete: (id: string) => `${BASE_URL}/api/sales/SalesTeam/${id}`,
    addMember: (id: string) => `${BASE_URL}/api/sales/SalesTeam/${id}/members`,
    removeMember: (id: string, memberId: string) => `${BASE_URL}/api/sales/SalesTeam/${id}/members/${memberId}`,
  },
};
