import { environment } from '@env';

const B = environment.apiBaseUrl;

export const PROCUREMENT_API = {
  geo: {
    currencies: `${B}/api/core/geo/currencies`,
  },

  // Cross-module lookups sourced from the Inventory module.
  inventory: {
    units: `${B}/api/Unit`,
    unitsActive: `${B}/api/Unit/active`,
    warehousesActive: `${B}/api/Warehouse/active`,
    warehouseBinsActive: (warehouseId: string) => `${B}/api/Warehouse/${warehouseId}/bins/active`,
    itemsBasic: `/api/Item/basic`, // relative — consumed by EntityPickerInputComponent (API mode)
  },

  vendor: {
    getAll: `${B}/api/v1/Vendor`,
    getById: (id: string) => `${B}/api/v1/Vendor/${id}`,
    getByNumber: (n: string) => `${B}/api/v1/Vendor/number/${n}`,
    getByStatus: (s: number) => `${B}/api/v1/Vendor/by-status/${s}`,
    getByOnboardingStatus: (s: number) => `${B}/api/v1/Vendor/by-onboarding-status/${s}`,
    getPreferred: `${B}/api/v1/Vendor/preferred`,
    getByCategory: (id: string) => `${B}/api/v1/Vendor/by-category/${id}`,
    create: `${B}/api/v1/Vendor`,
    update: (id: string) => `${B}/api/v1/Vendor/${id}`,
    approve: (id: string) => `${B}/api/v1/Vendor/${id}/approve`,
    deactivate: (id: string) => `${B}/api/v1/Vendor/${id}/deactivate`,
    reactivate: (id: string) => `${B}/api/v1/Vendor/${id}/reactivate`,
    block: (id: string) => `${B}/api/v1/Vendor/${id}/block`,
    unblock: (id: string) => `${B}/api/v1/Vendor/${id}/unblock`,
    delete: (id: string) => `${B}/api/v1/Vendor/${id}`,
    addContact: (vid: string) => `${B}/api/v1/Vendor/${vid}/contacts`,
    updateContact: (vid: string, cid: string) => `${B}/api/v1/Vendor/${vid}/contacts/${cid}`,
    deleteContact: (vid: string, cid: string) => `${B}/api/v1/Vendor/${vid}/contacts/${cid}`,
    addAddress: (vid: string) => `${B}/api/v1/Vendor/${vid}/addresses`,
    updateAddress: (vid: string, aid: string) => `${B}/api/v1/Vendor/${vid}/addresses/${aid}`,
    deleteAddress: (vid: string, aid: string) => `${B}/api/v1/Vendor/${vid}/addresses/${aid}`,
    addBankAccount: (vid: string) => `${B}/api/v1/Vendor/${vid}/bank-accounts`,
    updateBankAccount: (vid: string, bid: string) => `${B}/api/v1/Vendor/${vid}/bank-accounts/${bid}`,
    deleteBankAccount: (vid: string, bid: string) => `${B}/api/v1/Vendor/${vid}/bank-accounts/${bid}`,
  },

  purchaseOrder: {
    getAll: `${B}/api/v1/PurchaseOrder`,
    getById: (id: string) => `${B}/api/v1/PurchaseOrder/${id}`,
    getByNumber: (n: string) => `${B}/api/v1/PurchaseOrder/number/${n}`,
    getByStatus: (s: number) => `${B}/api/v1/PurchaseOrder/by-status/${s}`,
    getByVendor: (id: string) => `${B}/api/v1/PurchaseOrder/by-vendor/${id}`,
    getPendingReceipt: `${B}/api/v1/PurchaseOrder/pending-receipt`,
    getToInvoice: `${B}/api/v1/PurchaseOrder/to-invoice`,
    create: `${B}/api/v1/PurchaseOrder`,
    update: (id: string) => `${B}/api/v1/PurchaseOrder/${id}`,
    confirm: (id: string) => `${B}/api/v1/PurchaseOrder/${id}/confirm`,
    sendToVendor: (id: string) => `${B}/api/v1/PurchaseOrder/${id}/send-to-vendor`,
    acknowledge: (id: string) => `${B}/api/v1/PurchaseOrder/${id}/acknowledge`,
    close: (id: string) => `${B}/api/v1/PurchaseOrder/${id}/close`,
    cancel: (id: string) => `${B}/api/v1/PurchaseOrder/${id}/cancel`,
    delete: (id: string) => `${B}/api/v1/PurchaseOrder/${id}`,
  },

  requisition: {
    getAll: `${B}/api/v1/PurchaseRequisition`,
    getById: (id: string) => `${B}/api/v1/PurchaseRequisition/${id}`,
    getByNumber: (n: string) => `${B}/api/v1/PurchaseRequisition/number/${n}`,
    getByStatus: (s: number) => `${B}/api/v1/PurchaseRequisition/by-status/${s}`,
    getByRequester: (uid: string) => `${B}/api/v1/PurchaseRequisition/by-requester/${uid}`,
    getByDepartment: (did: string) => `${B}/api/v1/PurchaseRequisition/by-department/${did}`,
    getPendingApproval: `${B}/api/v1/PurchaseRequisition/pending-approval`,
    create: `${B}/api/v1/PurchaseRequisition`,
    update: (id: string) => `${B}/api/v1/PurchaseRequisition/${id}`,
    submit: (id: string) => `${B}/api/v1/PurchaseRequisition/${id}/submit`,
    approve: (id: string) => `${B}/api/v1/PurchaseRequisition/${id}/approve`,
    reject: (id: string) => `${B}/api/v1/PurchaseRequisition/${id}/reject`,
    cancel: (id: string) => `${B}/api/v1/PurchaseRequisition/${id}/cancel`,
    convertToOrder: (id: string) => `${B}/api/v1/PurchaseRequisition/${id}/convert-to-order`,
    delete: (id: string) => `${B}/api/v1/PurchaseRequisition/${id}`,
  },

  rfq: {
    getAll: `${B}/api/v1/RequestForQuotation`,
    getById: (id: string) => `${B}/api/v1/RequestForQuotation/${id}`,
    getByNumber: (n: string) => `${B}/api/v1/RequestForQuotation/number/${n}`,
    getByStatus: (s: number) => `${B}/api/v1/RequestForQuotation/by-status/${s}`,
    getByRequisition: (rid: string) => `${B}/api/v1/RequestForQuotation/by-requisition/${rid}`,
    create: `${B}/api/v1/RequestForQuotation`,
    update: (id: string) => `${B}/api/v1/RequestForQuotation/${id}`,
    send: (id: string) => `${B}/api/v1/RequestForQuotation/${id}/send`,
    close: (id: string) => `${B}/api/v1/RequestForQuotation/${id}/close`,
    cancel: (id: string) => `${B}/api/v1/RequestForQuotation/${id}/cancel`,
    delete: (id: string) => `${B}/api/v1/RequestForQuotation/${id}`,
    submitQuotation: (rfqId: string) => `${B}/api/v1/RequestForQuotation/${rfqId}/quotations`,
    evaluate: (rfqId: string) => `${B}/api/v1/RequestForQuotation/${rfqId}/evaluate`,
    award: (rfqId: string, quotationId: string) => `${B}/api/v1/RequestForQuotation/${rfqId}/award/${quotationId}`,
  },

  goodsReceipt: {
    getAll: `${B}/api/v1/GoodsReceipt`,
    getById: (id: string) => `${B}/api/v1/GoodsReceipt/${id}`,
    getByNumber: (n: string) => `${B}/api/v1/GoodsReceipt/number/${n}`,
    getByStatus: (s: number) => `${B}/api/v1/GoodsReceipt/by-status/${s}`,
    getByPO: (poId: string) => `${B}/api/v1/GoodsReceipt/by-purchase-order/${poId}`,
    getByVendor: (vid: string) => `${B}/api/v1/GoodsReceipt/by-vendor/${vid}`,
    create: `${B}/api/v1/GoodsReceipt`,
    update: (id: string) => `${B}/api/v1/GoodsReceipt/${id}`,
    post: (id: string) => `${B}/api/v1/GoodsReceipt/${id}/post`,
    cancel: (id: string) => `${B}/api/v1/GoodsReceipt/${id}/cancel`,
    inspect: (id: string) => `${B}/api/v1/GoodsReceipt/${id}/inspect`,
    delete: (id: string) => `${B}/api/v1/GoodsReceipt/${id}`,
  },

  invoice: {
    getAll: `${B}/api/v1/PurchaseInvoice`,
    getById: (id: string) => `${B}/api/v1/PurchaseInvoice/${id}`,
    getByNumber: (n: string) => `${B}/api/v1/PurchaseInvoice/number/${n}`,
    getByStatus: (s: number) => `${B}/api/v1/PurchaseInvoice/by-status/${s}`,
    getByVendor: (vid: string) => `${B}/api/v1/PurchaseInvoice/by-vendor/${vid}`,
    getByPO: (poId: string) => `${B}/api/v1/PurchaseInvoice/by-purchase-order/${poId}`,
    getOverdue: `${B}/api/v1/PurchaseInvoice/overdue`,
    getPendingPayment: `${B}/api/v1/PurchaseInvoice/pending-payment`,
    create: `${B}/api/v1/PurchaseInvoice`,
    update: (id: string) => `${B}/api/v1/PurchaseInvoice/${id}`,
    approve: (id: string) => `${B}/api/v1/PurchaseInvoice/${id}/approve`,
    post: (id: string) => `${B}/api/v1/PurchaseInvoice/${id}/post`,
    hold: (id: string) => `${B}/api/v1/PurchaseInvoice/${id}/hold`,
    releaseHold: (id: string) => `${B}/api/v1/PurchaseInvoice/${id}/release-hold`,
    dispute: (id: string) => `${B}/api/v1/PurchaseInvoice/${id}/dispute`,
    resolveDispute: (id: string) => `${B}/api/v1/PurchaseInvoice/${id}/resolve-dispute`,
    cancel: (id: string) => `${B}/api/v1/PurchaseInvoice/${id}/cancel`,
    threeWayMatch: (id: string) => `${B}/api/v1/PurchaseInvoice/${id}/three-way-match`,
    delete: (id: string) => `${B}/api/v1/PurchaseInvoice/${id}`,
  },

  payment: {
    getAll: `${B}/api/v1/VendorPayment`,
    getById: (id: string) => `${B}/api/v1/VendorPayment/${id}`,
    getByNumber: (n: string) => `${B}/api/v1/VendorPayment/number/${n}`,
    getByStatus: (s: number) => `${B}/api/v1/VendorPayment/by-status/${s}`,
    getByVendor: (vid: string) => `${B}/api/v1/VendorPayment/by-vendor/${vid}`,
    create: `${B}/api/v1/VendorPayment`,
    update: (id: string) => `${B}/api/v1/VendorPayment/${id}`,
    approve: (id: string) => `${B}/api/v1/VendorPayment/${id}/approve`,
    markSent: (id: string) => `${B}/api/v1/VendorPayment/${id}/mark-sent`,
    clear: (id: string) => `${B}/api/v1/VendorPayment/${id}/clear`,
    cancel: (id: string) => `${B}/api/v1/VendorPayment/${id}/cancel`,
    delete: (id: string) => `${B}/api/v1/VendorPayment/${id}`,
  },

  contract: {
    getAll: `${B}/api/v1/PurchaseContract`,
    getById: (id: string) => `${B}/api/v1/PurchaseContract/${id}`,
    getByNumber: (n: string) => `${B}/api/v1/PurchaseContract/number/${n}`,
    getByStatus: (s: number) => `${B}/api/v1/PurchaseContract/by-status/${s}`,
    getByVendor: (vid: string) => `${B}/api/v1/PurchaseContract/by-vendor/${vid}`,
    getActive: `${B}/api/v1/PurchaseContract/active`,
    getExpiring: (days: number) => `${B}/api/v1/PurchaseContract/expiring?withinDays=${days}`,
    create: `${B}/api/v1/PurchaseContract`,
    update: (id: string) => `${B}/api/v1/PurchaseContract/${id}`,
    activate: (id: string) => `${B}/api/v1/PurchaseContract/${id}/activate`,
    suspend: (id: string) => `${B}/api/v1/PurchaseContract/${id}/suspend`,
    terminate: (id: string) => `${B}/api/v1/PurchaseContract/${id}/terminate`,
    renew: (id: string) => `${B}/api/v1/PurchaseContract/${id}/renew`,
    delete: (id: string) => `${B}/api/v1/PurchaseContract/${id}`,
  },

  vendorCategory: {
    getAll: `${B}/api/v1/VendorCategory`,
    getActive: `${B}/api/v1/VendorCategory/active`,
    getById: (id: string) => `${B}/api/v1/VendorCategory/${id}`,
    create: `${B}/api/v1/VendorCategory`,
    update: (id: string) => `${B}/api/v1/VendorCategory/${id}`,
    delete: (id: string) => `${B}/api/v1/VendorCategory/${id}`,
  },

  procurementCategory: {
    getAll: `${B}/api/v1/ProcurementCategory`,
    getActive: `${B}/api/v1/ProcurementCategory/active`,
    getTree: `${B}/api/v1/ProcurementCategory/tree`,
    getById: (id: string) => `${B}/api/v1/ProcurementCategory/${id}`,
    create: `${B}/api/v1/ProcurementCategory`,
    update: (id: string) => `${B}/api/v1/ProcurementCategory/${id}`,
    delete: (id: string) => `${B}/api/v1/ProcurementCategory/${id}`,
  },

  vendorDocument: {
    getAll: (vid: string) => `${B}/api/v1/vendors/${vid}/documents`,
    getById: (vid: string, id: string) => `${B}/api/v1/vendors/${vid}/documents/${id}`,
    create: (vid: string) => `${B}/api/v1/vendors/${vid}/documents`,
    update: (vid: string, id: string) => `${B}/api/v1/vendors/${vid}/documents/${id}`,
    verify: (vid: string, id: string) => `${B}/api/v1/vendors/${vid}/documents/${id}/verify`,
    delete: (vid: string, id: string) => `${B}/api/v1/vendors/${vid}/documents/${id}`,
    getExpiring: (days: number) => `${B}/api/v1/vendor-documents/expiring?withinDays=${days}`,
  },

  vendorPricelist: {
    getAll: (vid: string) => `${B}/api/v1/vendors/${vid}/pricelists`,
    getById: (vid: string, id: string) => `${B}/api/v1/vendors/${vid}/pricelists/${id}`,
    create: (vid: string) => `${B}/api/v1/vendors/${vid}/pricelists`,
    update: (vid: string, id: string) => `${B}/api/v1/vendors/${vid}/pricelists/${id}`,
    delete: (vid: string, id: string) => `${B}/api/v1/vendors/${vid}/pricelists/${id}`,
  },

  reports: {
    purchaseAnalysis: `${B}/api/v1/procurement/reports/purchase-analysis`,
    vendorAnalysis: `${B}/api/v1/procurement/reports/vendor-analysis`,
    apAging: `${B}/api/v1/procurement/reports/ap-aging`,
    threeWayMatch: `${B}/api/v1/procurement/reports/three-way-match`,
    spendByCategory: `${B}/api/v1/procurement/reports/spend-by-category`,
  },

  landedCost: {
    getAll: `${B}/api/v1/LandedCost`,
    getById: (id: string) => `${B}/api/v1/LandedCost/${id}`,
    create: `${B}/api/v1/LandedCost`,
    post: (id: string) => `${B}/api/v1/LandedCost/${id}/post`,
    cancel: (id: string) => `${B}/api/v1/LandedCost/${id}/cancel`,
    delete: (id: string) => `${B}/api/v1/LandedCost/${id}`,
  },

  vendorDebitNote: {
    getAll: `${B}/api/v1/VendorDebitNote`,
    getById: (id: string) => `${B}/api/v1/VendorDebitNote/${id}`,
    getByVendor: (vid: string) => `${B}/api/v1/VendorDebitNote/by-vendor/${vid}`,
    eligibleReturns: `${B}/api/v1/VendorDebitNote/eligible-returns`,
    create: `${B}/api/v1/VendorDebitNote`,
    send: (id: string) => `${B}/api/v1/VendorDebitNote/${id}/send`,
    acknowledge: (id: string) => `${B}/api/v1/VendorDebitNote/${id}/acknowledge`,
    settle: (id: string) => `${B}/api/v1/VendorDebitNote/${id}/settle`,
    cancel: (id: string) => `${B}/api/v1/VendorDebitNote/${id}/cancel`,
    delete: (id: string) => `${B}/api/v1/VendorDebitNote/${id}`,
  },

  purchaseReturn: {
    getAll: `${B}/api/v1/PurchaseReturn`,
    getById: (id: string) => `${B}/api/v1/PurchaseReturn/${id}`,
    getByVendor: (vid: string) => `${B}/api/v1/PurchaseReturn/by-vendor/${vid}`,
    create: `${B}/api/v1/PurchaseReturn`,
    approve: (id: string) => `${B}/api/v1/PurchaseReturn/${id}/approve`,
    post: (id: string) => `${B}/api/v1/PurchaseReturn/${id}/post`,
    cancel: (id: string) => `${B}/api/v1/PurchaseReturn/${id}/cancel`,
    delete: (id: string) => `${B}/api/v1/PurchaseReturn/${id}`,
  },

  approvedVendorList: {
    getAll: `${B}/api/v1/ApprovedVendorList`,
    getById: (id: string) => `${B}/api/v1/ApprovedVendorList/${id}`,
    getByVendor: (vid: string) => `${B}/api/v1/ApprovedVendorList/by-vendor/${vid}`,
    getByItem: (id: string) => `${B}/api/v1/ApprovedVendorList/by-item/${id}`,
    getByCategory: (id: string) => `${B}/api/v1/ApprovedVendorList/by-category/${id}`,
    create: `${B}/api/v1/ApprovedVendorList`,
    update: (id: string) => `${B}/api/v1/ApprovedVendorList/${id}`,
    block: (id: string) => `${B}/api/v1/ApprovedVendorList/${id}/block`,
    unblock: (id: string) => `${B}/api/v1/ApprovedVendorList/${id}/unblock`,
    delete: (id: string) => `${B}/api/v1/ApprovedVendorList/${id}`,
  },

  vendorPerformance: {
    getAll: `${B}/api/v1/VendorPerformance`,
    getById: (id: string) => `${B}/api/v1/VendorPerformance/${id}`,
    getByVendor: (vid: string) => `${B}/api/v1/VendorPerformance/by-vendor/${vid}`,
    create: `${B}/api/v1/VendorPerformance`,
    update: (id: string) => `${B}/api/v1/VendorPerformance/${id}`,
    delete: (id: string) => `${B}/api/v1/VendorPerformance/${id}`,
  },

  approvalWorkflow: {
    getAll: `${B}/api/v1/ApprovalWorkflow`,
    getByDocumentType: (dt: number) => `${B}/api/v1/ApprovalWorkflow/by-document-type/${dt}`,
    getById: (id: string) => `${B}/api/v1/ApprovalWorkflow/${id}`,
    create: `${B}/api/v1/ApprovalWorkflow`,
    update: (id: string) => `${B}/api/v1/ApprovalWorkflow/${id}`,
    delete: (id: string) => `${B}/api/v1/ApprovalWorkflow/${id}`,
  },

  documentSequence: {
    getAll: `${B}/api/v1/DocumentSequence`,
    getByDocumentType: (dt: number) => `${B}/api/v1/DocumentSequence/by-document-type/${dt}`,
    update: (id: string) => `${B}/api/v1/DocumentSequence/${id}`,
  },

  settings: {
    get: `${B}/api/v1/procurement/settings`,
    update: `${B}/api/v1/procurement/settings`,
  },

  lookups: {
    getAll: `${B}/api/v1/procurement/lookups/all`,
    paymentTerms: `${B}/api/v1/procurement/lookups/payment-terms`,
    incoterms: `${B}/api/v1/procurement/lookups/incoterms`,
    vendorStatuses: `${B}/api/v1/procurement/lookups/vendor-statuses`,
    requisitionStatuses: `${B}/api/v1/procurement/lookups/requisition-statuses`,
    requisitionPriorities: `${B}/api/v1/procurement/lookups/requisition-priorities`,
    rfqStatuses: `${B}/api/v1/procurement/lookups/rfq-statuses`,
    quotationStatuses: `${B}/api/v1/procurement/lookups/quotation-statuses`,
    grnStatuses: `${B}/api/v1/procurement/lookups/goods-receipt-statuses`,
    receiptTypes: `${B}/api/v1/procurement/lookups/receipt-types`,
    qualityStatuses: `${B}/api/v1/procurement/lookups/quality-inspection-statuses`,
    invoiceStatuses: `${B}/api/v1/procurement/lookups/purchase-invoice-statuses`,
    paymentStatuses: `${B}/api/v1/procurement/lookups/vendor-payment-statuses`,
    paymentMethods: `${B}/api/v1/procurement/lookups/vendor-payment-methods`,
    contractStatuses: `${B}/api/v1/procurement/lookups/purchase-contract-statuses`,
    contractTypes: `${B}/api/v1/procurement/lookups/purchase-contract-types`,
    approvalDocumentTypes: `${B}/api/v1/procurement/lookups/approval-document-types`,
    documentTypes: `${B}/api/v1/procurement/lookups/document-types`,
    sequenceResetPeriods: `${B}/api/v1/procurement/lookups/sequence-reset-periods`,
    vendorDocumentTypes: `${B}/api/v1/procurement/lookups/vendor-document-types`,
    vendorDocumentStatuses: `${B}/api/v1/procurement/lookups/vendor-document-statuses`,
  },
};
